/**
 * Control module — authored in the spec (ADR-0002).
 *
 * Generated by `spec:scaffold-module Control` from the hand-written
 * datamodel.json, then hand-maintained. Edit here and run `npm run build`;
 * never edit this module in the JSON (the CI drift guard rejects it).
 */
import { attr, computed, concat, defineModule, entity, enumOf, fk, mirror, rollup, table, userInput } from "../authoring.js";
import { requires, requiresValue } from "../behavior/check.js";
import { formFor } from "../view/form.js";

const capacity = entity("Capacity", "Query view (Control module) — no new-item form. Aggregates role/department capacity against allocation over a planning period (ISO §7.1.2 / §6.2).", [
  attr("capacityID", "INT", { constraints: ["PK"], show: [false, false] }),
  attr("functionID", "FK", { rel: fk("Functions", { display: "functionName" }), notes: "The grain key (issue #246, A3): Capacity = functionID × year × month — the old department × role × function × customer mix was ambiguous. Rows are OUTPUTS of tools/derive_control.py, never hand-seeded; the validator recomputes and compares.", constraints: ["FK","NOT NULL"], show: [true, true] }),
  attr("functionName", "mirror", { rel: mirror("Functions", "functionID", { display: "functionName" }), notes: "Display twin of functionID (issue #246). Used by Report-A/B filters.", show: [true, true] }),
  attr("periodType", "ENUM", { rel: enumOf("Annual", "Quarter", "Month"), show: [true, true] }),
  attr("periodYear", "INT", { show: [true, true] }),
  attr("periodQuarter", "INT", { notes: "nullable", show: [true, true] }),
  attr("periodMonth", "INT", { notes: "nullable", show: [true, true] }),
  attr("periodStart", "DATETIME", { notes: "Start month/year of report analysis", show: [true, true] }),
  attr("periodFinish", "DATETIME", { notes: "End month/year of report analysis", show: [true, true] }),
  attr("availableHours", "DECIMAL", { notes: "DERIVED by tools/derive_control.py (issue #246): Σ People.workingHours (weekly) of the function × weeks of the month (periodBusinessDays/5). The validator recomputes and compares — divergence fails the build.", show: [true, true] }),
  attr("allocatedHours", "DECIMAL", { notes: "DERIVED by tools/derive_control.py (issue #246): Σ Forecast Scopes.estimatedHours of the function in the month's forecasts — totalEstimatedHours decomposed by function, finally matching the live Report-A recomputation (A3 killed the 60/60 divergence).", show: [true, true] }),
  attr("utilization", "DECIMAL", { rel: computed(null), notes: "Displayed as %", show: [true, true] }),
  attr("customerID", "FK", { rel: fk("Customers", { display: "customerName" }), notes: "Attribution, not grain (issue #246): the customer consuming the MOST of this function's allocated hours in the month — feeds Card 1-2's gap reading", constraints: ["FK"], show: [true, true] }),
  attr("capacityOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c))", constraints: ["FK"], show: [false, false] }),
]);

const performance = entity("Performance", "Query view (Control module) — no new-item form. Tracks actual resource consumption from Jobs against planned Forecast Scope hours (ISO §9.1).", [
  attr("usageID", "INT", { constraints: ["PK"], show: [false, false] }),
  attr("functionID", "FK", { rel: fk("Functions", { display: "functionName" }), notes: "Grain key (issue #246, A3): Performance = functionID × customerID × year × month over DONE jobs — the old region × department × ticket × squad mix was ambiguous. Rows are OUTPUTS of tools/derive_control.py; the validator recomputes and compares.", constraints: ["FK","NOT NULL"], show: [true, true] }),
  attr("functionName", "mirror", { rel: mirror("Functions", "functionID", { display: "functionName" }), notes: "Display twin of functionID (issue #246). Used by Report-A/B filters and series.", show: [true, true] }),
  attr("customerID", "FK", { rel: fk("Customers", { display: "customerName" }), notes: "Grain key (issue #246): the customer whose jobs feed this row", constraints: ["FK","NOT NULL"], show: [true, true] }),
  attr("customerName", "mirror", { rel: mirror("Customers", "customerID", { display: "customerName" }), notes: "Display twin of customerID (issue #246). Used by Report-A/B filters.", show: [true, true] }),
  attr("periodType", "ENUM", { rel: enumOf("Annual", "Quarter", "Month"), show: [true, true] }),
  attr("periodYear", "INT", { show: [true, true] }),
  attr("periodMonth", "INT", { show: [true, true] }),
  attr("plannedHours", "DECIMAL", { notes: "DERIVED by tools/derive_control.py (issue #246): Σ Jobs.plannedExecutionTime of the group's Done jobs in the month — the flat invented 516 h/month is gone (A3)", show: [true, true] }),
  attr("realExecutionTime", "DECIMAL", { notes: "DERIVED by tools/derive_control.py (issue #246): Σ Jobs.realExecutionTime of the group's Done jobs in the month", show: [true, true] }),
  attr("efficiency", "DECIMAL", { rel: computed(null), notes: "Value in %" }),
  attr("variance", "DECIMAL", { rel: computed("variance of realExecutionTime per job"), notes: "DERIVED by tools/derive_control.py (issue #246): population variance of the group's per-job real hours" }),
  attr("reportedAt", "DATETIME", { show: [true, true] }),
  attr("reportedBy", "FK", { rel: fk("People", { display: "userName" }), constraints: ["FK"], show: [true, true] }),
  attr("performanceOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c))", constraints: ["FK"], show: [false, false] }),
]);

export const control = defineModule("Control", 7, [
  table(capacity, {
    visibility: "show",
    dashboardOrder: 1,
    reports: {
      "Report-A": {
        "overview-display": true,
        "graph_type": "bar chart - multiple",
        "rule": "availableHours vs. allocatedHours side by side grouped by functionName. Y = hours, X = functionName. Apply the weeklyUsageQuota for allocatedHours time framing for the period selected in the filter",
        "filters": {
          "fields": {
            "periodFrame": {
              "field-type": {
                "range-picker": "shadcn-Date Picker"
              },
              "tooltip": null,
              "default": "last six months from current date",
              "check": null,
              "field-rule": null
            },
            "scopeName": {
              "field-type": {
                "basic": "shadcn-combobox"
              },
              "tooltip": null,
              "default": "ALL",
              "check": null,
              "field-rule": "computed -> Scopes (via: eventTitle.field), (display: scopeName):  Multivalued field"
            },
            "eventTitle": {
              "field-type": {
                "combobox": "shadcn-comboboxGroups"
              },
              "tooltip": null,
              "default": "ALL",
              "check": null,
              "field-rule": "FK -> Events (display: eventName): Multivalued field"
            },
            "customerName": {
              "field-type": {
                "combobox": "shadcn-combobox"
              },
              "tooltip": null,
              "default": "ALL",
              "check": null,
              "field-rule": "FK -> Customers (display: customerName): Multivalued field"
            }
          }
        }
      }
    },
    form: false,
    cards: {
      "Card 1-1": {
        "overview-display": true,
        "title": "Capacity Utilization",
        "card-rules": {
          "main-data": "Show the total `utilization` amount",
          "trend-data": "how much the utilization has changed during the last 3 months",
          "detail-data": "allocatedHours / availableHours "
        },
        "card-component": "shadcn-card",
        "card-tooltip": "Percentage alignment between customer‑forecasted hours and planned workload."
      },
      "Card 1-2": {
        "title": "Most Overestimated Customer",
        "card-rules": {
          "main-data": "customerName with the biggest utilization gap",
          "trend-data": null,
          "detail-data": "customerName utilization gap vs the medium utilization gap"
        },
        "card-component": "shadcn-card",
        "card-tooltip": "Cliente que menos utilizou dos product scopes previstos em seus forecasts"
      }
    },
    tableFilters: null,
    subitemTables: null,
  }),
  table(performance, {
    visibility: "show",
    dashboardOrder: 2,
    reports: {
      "Report-A": {
        "overview-display": true,
        "graph_type": "bar chart - multiple",
        "rule": "plannedHours vs. realExecutionTime side by side grouped by customerName. Y = hours, X = customerName",
        "filters": {
          "fields": {
            "periodFrame": {
              "field-type": {
                "range-picker": "shadcn-Date Picker"
              },
              "tooltip": null,
              "default": "last six months from current date",
              "check": null,
              "field-rule": null
            },
            "scopeName": {
              "field-type": {
                "basic": "shadcn-combobox"
              },
              "tooltip": null,
              "default": "ALL",
              "check": null,
              "field-rule": "computed -> Scopes (via: eventTitle.field), (display: scopeName):  Multivalued field"
            },
            "eventTitle": {
              "field-type": {
                "combobox": "shadcn-comboboxGroups"
              },
              "tooltip": null,
              "default": "ALL",
              "check": null,
              "field-rule": "FK -> Events (display: eventName): Multivalued field"
            }
          }
        }
      },
      "Report-B": {
        "graph_type": "bar chart",
        "rule": "variance by processName. Y = variance, X = processName",
        "filters": {
          "fields": {
            "periodFrame": {
              "field-type": {
                "range-picker": "shadcn-Date Picker"
              },
              "tooltip": null,
              "default": "last six months from current date",
              "check": null,
              "field-rule": null
            },
            "productScopeID": {
              "field-type": {
                "basic": "shadcn-combobox"
              },
              "tooltip": null,
              "default": "ALL",
              "check": null,
              "field-rule": "computed -> Product Scopes (via: ticketID), (display: productScopeName):  Multivalued field"
            }
          }
        }
      }
    },
    form: false,
    cards: {
      "Card 1-1": {
        "title": "Standard Deviation Bottleneck",
        "card-rules": {
          "main-data": "highest jobs realExecutionTime standad deviation in hours grouped by processID",
          "trend-data": null,
          "detail-data": "processName - jobs median realExecutionTime in hours X jobs realExecutionTime variance"
        },
        "card-component": "shadcn-card",
        "card-tooltip": "Process with the highest job execution standard variation levels."
      },
      "Card 1-2": {
        "overview-display": true,
        "title": "Job Execution Performance",
        "card-rules": {
          "main-data": "((plannedHours/realExecutionTime)-1)*100 for all jobs",
          "trend-data": "trend for the past 3 months",
          "detail-data": "total plannedHours / total realExecutionTime in hours"
        },
        "card-component": "shadcn-card",
        "card-tooltip": "Rate of jobs execution against planned hours."
      }
    },
    tableFilters: null,
    subitemTables: null,
  }),
], {
  suppress: {
    "Performance.variance": "#417: computed target \"variance of realExecutionTime per job\" is not an entity (malformed rule?)"
  },
});
