/**
 * CRM module — authored in the spec (ADR-0002).
 *
 * Generated by `spec:scaffold-module CRM` from the hand-written
 * datamodel.json, then hand-maintained. Edit here and run `npm run build`;
 * never edit this module in the JSON (the CI drift guard rejects it).
 */
import { attr, computed, concat, defineModule, entity, enumOf, fk, mirror, rollup, table, userInput } from "../authoring.js";
import { requires, requiresValue } from "../behavior/check.js";
import { formFor } from "../view/form.js";

const customers = entity("Customers", "Interested parties the division serves (ISO §4.1/§4.2): paying customers (insurers, partner hospitals) and internal clients (the network's own units), classified by business segment and unit.", [
  attr("customerID", "INT", { notes: "Auto-generated primary key", constraints: ["PK"], show: [false, false] }),
  attr("customerName", "VARCHAR", { notes: "Short code, e.g. \"PN\"", show: [true, true] }),
  attr("businessSegmentID", "FK", { rel: fk("Business Segments", { display: "businessSegmentName" }), notes: "multivalued — user-selected (reverts decision Q4, 2026-07-30)", constraints: ["NOT NULL"], show: [true, true] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "multivalued — user-selected, filtered by the chosen segments (PR #96 cascade)", constraints: ["NOT NULL"], show: [true, true] }),
  attr("branchID", "mirror", { rel: rollup("Branches", "customerID", { display: "branchName" }), notes: "Multivalued — branches registered to this customer. AUTHORED HERE: the Customer form's Branch picker writes the customer into Branches.customerID on save (applyCustomerBranches); nothing is stored on the Customer record. N:N since 2026-09-04 (schema v74): a branch may serve several customers — every branch stays offered and the save touches only this customer's own membership (the v73 ownership guard was retired the same day). Geography (city/country/region) lives on the Branches since issue #191 dropped the redundant Customer copies." }),
  attr("customerType", "ENUM", { rel: enumOf("Internal", "External"), notes: "Relationship of this customer to the organisation (issue #191 relabel — was branch/client/supplier)" }),
  attr("isActive", "BOOLEAN", { notes: "Soft-delete flag", show: [true, true] }),
  attr("forecastID", "rollup", { rel: rollup("Forecasts", "customerID"), notes: "All forecast records belonging to this customer", show: [false, false] }),
  attr("scopeName", "mirror", { rel: mirror("Forecast Scopes", "forecastID"), notes: "All forecast records belonging to this customer", show: [false, false] }),
  attr("customerOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c))", constraints: ["FK"], show: [false, false] }),
]);

const sla = entity("SLA", "Service Level Agreement (ISO §8.2) — the contract by which a Customer purchases Payloads supplied by a Department of the Supplier (2026-09-03 round; the branch identifies the supplier, the supplier's department supplies the payloads): tickets the customer opens can only trigger events covered by one of the customer's SLAs (issue #179).", [
  attr("slaID", "INT", { notes: "Auto-generated primary key", constraints: ["PK"], show: [false, false] }),
  attr("slaCode", "VARCHAR", { notes: "Contract ID or code, e.g. \"SLA-0001\"", constraints: ["NOT NULL"], show: [true, true] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "single valued — the providing unit", constraints: ["FK","NOT NULL"] }),
  attr("customerID", "FK", { rel: fk("Customers", { display: "customerName" }), notes: "the contracting customer — join anchor for the Customers subitem and the Projects chain (#192); see supplierID for the supplying side (#272)", constraints: ["FK","NOT NULL"] }),
  attr("supplierID", "FK", { rel: fk("Customers", { display: "customerName" }), notes: "the supplying party of the contract (issue #272; 2026-09-03 round) — the supplier inside the selected branch: the form offers the customers registered at the branch (Branches.customerID, multivalued since the v74 N:N round — every linked customer is a candidate; bespoke suppliersForBranch), every customer grouped by type when no branch is chosen or the branch has no customer (lenient)", constraints: ["FK","NOT NULL"] }),
  attr("branchID", "FK", { rel: fk("Branches", { display: "branchName" }), notes: "the customer's contracting branch — nullable, a customer may have no branch", constraints: ["FK"], show: [false, false] }),
  attr("departmentID", "FK", { rel: fk("Departments", { display: "departmentName" }), notes: "the supplier's department that will supply the payloads (2026-09-03 round, was the unit's providing department) — the form filters to the departments of the supplier's units (generic shared-unit join: Customers.businessUnitID × Departments.businessUnitID)", constraints: ["FK","NOT NULL"], show: [true, true] }),
  attr("slaTitle", "mirror", { rel: concat("slaCode", {"lit":"-"}, "businessUnitName", {"lit":"-"}, "departmentName"), notes: "display helper (label attr) — downstream FK displays resolve it (Projects/Tickets, #192)", show: [false, false] }),
  attr("payloadID", "FK", { rel: fk("Payload", { display: "payloadCode" }), notes: "multivalued — the payloads the customer purchases (spec wrote a rollup — normalized to a stored FK, the picker must store PKs)", constraints: ["FK"], show: [false, false] }),
  attr("eventID", "mirror", { rel: computed("Payload", { via: "payloadID", display: "eventTitle" }), notes: "events the customer can open tickets for — derives through the purchased payloads", show: [true, true] }),
  attr("productScopeRegistry", "mirror", { rel: computed("Payload", { via: "payloadID", display: "productScopeRegistry" }), notes: "product scopes covered — derives through the payloads", constraints: ["multivalued"], show: [true, true] }),
  attr("isActive", "ENUM", { rel: enumOf("Active", "Inactive"), show: [true, true] }),
  attr("slaOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "ISO §5.3 — seeded from the providing unit's quality manager, no form input", constraints: ["FK"], show: [false, false] }),
]);

const forecasts = entity("Forecasts", "A Forecast (ISO §6.1) groups a set of Forecast Scopes — the temporal dimension of a contract (SLA): the customer projects its intended use of the division's role resources for a planning period.", [
  attr("forecastID", "INT", { notes: "Auto-generated primary key", constraints: ["PK"], show: [false, true] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "Form filter — narrows the SLA options (pre-RBAC filter input, issue #346). Stored FK; the hidden businessUnitName mirror stays for the Forecast Scopes grouping. Seeds: the SLA's unit (tools/migrate_prerbac_batch.py).", constraints: ["FK"], show: [false, false] }),
  attr("slaID", "FK", { rel: fk("SLA", { display: "slaTitle" }), notes: "The contract this forecast gives temporal dimension to (SLA 1:N Forecasts — SLA-as-Contract decision, issue #241). Customer derives from it on save.", constraints: ["FK","NOT NULL"], show: [true, true] }),
  attr("customerID", "FK", { rel: fk("Customers"), notes: "Customer of the contract — stored anchor for the downstream join chains (the Forecast Scopes requirement path traverses it), derived on save from the SLA since issue #241; no form field", constraints: ["FK","NOT NULL"], show: [false, false] }),
  attr("customerTitle", "mirror", { rel: mirror("Customers", "customerID", { display: "customerName" }), notes: "Customer of the contract (resolves customerName — the CONCAT customerTitle left Customers with the geography attrs, issue #191)" }),
  attr("businessUnitName", "mirror", { rel: mirror("SLA", "slaID", { display: "businessUnitName" }), notes: "Business Unit of the contract (the SLA stores it single-valued — sharper than the customer's multivalued units, issue #241) — groups the Forecast select on the Forecast Scopes form", show: [false, false] }),
  attr("forecastPeriod", "ENUM", { rel: enumOf("Annual", "Quarter", "Month"), notes: "Granularity of the period", constraints: ["NOT NULL"], show: [true, true] }),
  attr("periodStart", "DATETIME", { notes: "Depends on forecastPeriod condition (month/quarter/annual)" }),
  attr("periodFinish", "DATETIME", { rel: computed("add periodType month quantity to startDate to find periodFinish"), notes: ["if periodType = annual and periodStart = Mar/2026, than periodFinish = Mar/2027","if periodType = quarter and periodStart = Mar/2026, than periodFinish = Jun/2026","if periodType = month and periodStart = Mar/2026, than periodFinish = Mar/2026"], show: [false, false] }),
  attr("periodBusinessDays", "INT", { rel: computed(null), notes: ["if periodType = annual and periodStart = Mar/2026, than periodBusinessDays=254","if periodType = quarter and periodStart = Mar/2026, than periodBusinessDays=85","if periodType = month and periodStart = Mar/2026, than periodBusinessDays=22"], show: [true, true] }),
  attr("periodFrame", "VARCHAR", { rel: {"kind":"format","srcField":"periodStart","pattern":"YYYY-MonthName"}, notes: "Month label of periodStart, e.g. 2025-June", show: [true, true] }),
  attr("weeklyUsageQuota", "INT", { rel: computed(null), notes: "IF periodType='month', than periodFrame=periodStart", show: [true, true] }),
  attr("forecastScopeID", "rollup", { rel: rollup("Forecast Scopes", "forecastID"), notes: "All child Forecast Scope records belonging to this forecast", show: [false, false] }),
  attr("scopeName", "mirror", { rel: mirror("Forecast Scopes", "forecastScopeID"), notes: "All child Forecast Scope records belonging to this forecast", show: [false, false] }),
  attr("totalEstimatedHours", "DECIMAL", { rel: {"kind":"sum","childAttr":"forecastScopes","field":"estimatedHours","multiplierField":null}, notes: "Total demand projected across all scopes", show: [true, true] }),
  attr("status", "ENUM", { rel: enumOf("Draft", "Submitted", "Approved", "Archived"), show: [true, true] }),
  attr("createdBy", "FK", { rel: fk("People", { display: "userName" }), constraints: ["FK"] }),
  attr("createdAt", "DATETIME"),
  attr("forecastOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c))", constraints: ["FK"], show: [false, false] }),
]);

const forecastScopes = entity("Forecast Scopes", "The atomic unit of a Forecast (ISO §6.1/§6.2). Specifies one Event × Product Scope combination; the Event determines the triggered Process and therefore the Tasks whose roles and execution times drive estimatedHours.", [
  attr("forecastScopeID", "INT", { notes: "Auto-generated primary key", constraints: ["PK"], show: [false, true] }),
  attr("forecastScopeRegistry", "VARCHAR", { notes: "Registry code, e.g. \"FSR-2025-0001\" (nullable)", show: [false, false] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "Form filter — narrows the Forecast options (pre-RBAC filter input, issue #346). Seeds: the forecast's SLA's unit (tools/migrate_prerbac_batch.py).", constraints: ["FK"], show: [false, false] }),
  attr("forecastID", "FK", { rel: fk("Forecasts", { concat: [{"field":"customerTitle"},{"lit":" | "},{"field":"periodFrame"}] }), notes: "Parent forecast", constraints: ["FK","NOT NULL"], show: [false, false] }),
  attr("customerTitle", "mirror", { rel: rollup("forecastID"), show: [true, true] }),
  attr("periodFrame", "mirror", { rel: rollup("forecastID"), show: [true, true] }),
  attr("eventID", "FK", { rel: fk("Events", { display: "eventTitle" }), notes: "Event that triggers the Process; determines the task list", constraints: ["FK"], show: [true, true] }),
  attr("productScopeID", "FK", { rel: fk("Product Scopes", { display: "productScopeName" }), notes: "The portfolio anchor (issue #242) — the same Event × Product Scope unit the SLA's Payloads dispatch. Options: the product scopes packaged by the forecast's SLA payloads for the chosen event (since issue #367 an unpackaged payload contributes nothing — the wildcard widening survives only on pre-sv100 snapshots). Scope and product group derive from it on save.", constraints: ["FK","NOT NULL"], show: [true, true] }),
  attr("scopeID", "FK", { rel: fk("Scopes", { display: "scopeName" }), notes: "Derived on save from the Product Scope since issue #242 (stored — the requirement chain traverses it); no form field", constraints: ["FK","NOT NULL"], show: [true, true] }),
  attr("productGroupID", "FK", { rel: fk("Product Groups", { display: "productGroupName" }), notes: "Derived on save from the Product Scope since issue #242 (stored — the requirement chain traverses it); no form field", constraints: ["FK"], show: [true, true] }),
  attr("requirementID", "computed", { rel: {"kind":"computed","target":"Requirements","via":"forecastID.customerID.businessUnitID.regionID","viaList":["forecastID.customerID.businessUnitID.regionID","forecastID.customerID.businessUnitID","forecastID.slaID.branchID","scopeID","productGroupID","productScopeID"],"display":"requirementName","concat":null,"filter":null}, notes: "Requirements linked to the row's scope + product group. Region leg = the customer's units' SERVED regions (Business Units.regionID — issue #230: Customers stopped storing regionID at #191, so the old customerID.regionID path resolved empty and the region dimension was dormant; units posture matches the #226 ticket inheritance). Branch leg (issue #353 — the branchID dimension activated): the contract's branch; an SLA without a branch resolves an empty path and the leg is skipped (multiViaJoin posture). Since issue #366 a requirement with an EMPTY key matches NO parent (the wildcard is retired — sv99 materialized the demo blanks; pre-sv99 snapshots keep the Q1 reading)", show: [true, true] }),
  attr("productScopeName", "mirror", { rel: mirror("Product Scopes", "productScopeID"), show: [false, false] }),
  attr("processID", "VARCHAR", { rel: computed("Events", { display: "processName" }), notes: "Process triggered by the selected Event", show: [false, false] }),
  attr("taskID", "rollup", { rel: {"kind":"rollup","target":"Tasks","via":"eventID","viaList":["eventID","productScopeID"],"display":null,"concat":null,"filter":null}, notes: "Tasks matching this event and product scope", show: [false, false] }),
  attr("functionID", "FK", { rel: fk("Functions", { display: "functionName" }), notes: "The function this demand line projects hours for (issue #242 — was the free-string functionName, the aggregation key of Capacity::Report-A; D6 doctrine kills the name join). Options: the functions of the tasks chained by the chosen event.", constraints: ["FK"], show: [false, false] }),
  attr("functionName", "mirror", { rel: mirror("Functions", "functionID", { display: "functionName" }), notes: "Display twin of functionID (issue #242)", show: [false, false] }),
  attr("estimatedHours", "DECIMAL", { rel: {"kind":"sum","childAttr":"taskID","field":"executionTime","multiplierField":"forecastScopeQuantity"}, notes: "Hours of the chained tasks × the projected quantity (issue #242 — quantity finally multiplies; tasks derive their time from Procedures). Stored values are re-stamped by the migration to the same equation.", show: [true, true] }),
  attr("region", "VARCHAR", { rel: {"kind":"mirror","target":"DISTINCT","via":null,"viaList":null,"display":null,"concat":null,"filter":null}, notes: "Region of the customer that owns the parent forecast (via forecastID → Customers.regionID → Regions). Used by Report-B.", show: [false, false] }),
  attr("forecastScopeQuantity", "INT", { notes: "amount of forecast scope to be used to calculate estimatedHours", show: [true, true] }),
  attr("consumption", "rollup", { rel: rollup("Tickets", "forecastScopeID"), notes: "How many tickets ran against this demand line (issue #243 — a real COUNT at last; the stored invented values were dropped by the migration)" }),
  attr("remaining", "mirror", { rel: {"kind":"diff","minuend":"forecastScopeQuantity","subtrahend":"consumption"}, notes: "Forecast balance (issue #243) — a number the user can check by counting the linked tickets", show: [true, true] }),
  attr("notes", "TEXT"),
  attr("forecastScopeOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c))", constraints: ["FK"], show: [false, false] }),
]);

export const crm = defineModule("CRM", 3, [
  table(customers, {
    visibility: "show",
    dashboardOrder: 1,
    reports: {
      "Report-A": {
        "graph_type": "bar chart",
        "rule": "Forecast totalEstimatedHours by customerName",
        "filters": {
          "fields": {
            "periodFrame": {
              "field-type": {
                "range-picker": "shadcn-Date Picker"
              },
              "tooltip": null,
              "default": "last six months from current date",
              "check": null,
              "field-rule": null
            },
            "scopeName": {
              "field-type": {
                "basic": "shadcn-combobox"
              },
              "tooltip": null,
              "default": "ALL",
              "check": null,
              "field-rule": "computed -> Scopes (via: forecasts), (display: scopeName):  Multivalued field"
            }
          }
        }
      }
    },
    form: formFor(customers.entity, {
      fields: {
        "Segment": { attribute: "businessSegmentID", rule: { multi: true } },
        "Unit": { attribute: "businessUnitID", check: requires("Segment"), rule: { filteredBy: "Segment" } },
        "Name": { attribute: "customerName", widget: "field" },
        "Type": { attribute: "customerType", tooltip: "Relationship to the organisation: internal, external" },
        "Branch": { attribute: "branchID", widget: "selectgroups", tooltip: "Branches this customer is registered at — a branch may serve several customers; saving updates only this customer's own links on the Branch records", check: requires("Unit"), rule: { list: true, groupBy: "businessUnitName", multi: true, filteredBy: "businessUnitID" } },
        "Active": { attribute: "isActive", tooltip: "Soft-delete flag — inactive customers stay registered but are retired from operation", rule: { default: "Yes" } },
      },
    }),
    cards: null,
    tableFilters: true,
    subitemTables: [
      "SLA"
    ],
  }),
  table(sla, {
    visibility: "show",
    dashboardOrder: 2,
    reports: null,
    form: formFor(sla.entity, {
      fields: {
        "Code": { attribute: "slaCode" },
        "Business Unit": { attribute: "businessUnitID", widget: "selectgroups", tooltip: "The unit providing the service", rule: { groupBy: "businessSegmentName" } },
        "Branch": { attribute: "branchID", tooltip: "The customer's contracting branch — optional", check: requires("Business Unit"), rule: { filteredBy: "businessUnitID" } },
        "Supplier": { attribute: "supplierID", widget: "selectgroups", tooltip: "The Supplier inside the branch selected", rule: { groupBy: "customerType", filteredBy: "branchID" } },
        "Supplier Department": { attribute: "departmentID", tooltip: "Department that will supply the payloads (events and product scopes)", rule: { filteredBy: "supplierID" } },
        "Customer": { attribute: "customerID", tooltip: "The contracting customer", check: requires("Business Unit"), rule: { groupBy: "customerType", filteredBy: "businessUnitID" } },
        "Payloads": { attribute: "payloadID", tooltip: "Payloads this SLA purchases — tickets may only trigger these events", check: requires("Business Unit"), rule: { list: true, groupBy: "eventTitle", multi: true, filteredBy: "departmentID" } },
        "Status": { attribute: "isActive", tooltip: "Make this SLA available across the operation" },
      },
    }),
    cards: null,
    tableFilters: true,
    subitemTables: [
      "Forecasts"
    ],
  }),
  table(forecasts, {
    visibility: "show",
    dashboardOrder: 3,
    reports: {
      "Report-A": {
        "overview-display": true,
        "graph_type": "bar chart - multiple",
        "rule": "Forecasts.forecastID.totalEstimatedHours vs Tickets.tickedID.ticketExecutionTime by customerName, Y = hours, X = customerName",
        "filters": {
          "fields": {
            "periodFrame": {
              "field-type": {
                "range-picker": "shadcn-Date Picker"
              },
              "tooltip": null,
              "default": "last six months from current date",
              "check": null,
              "field-rule": null
            },
            "scopeName": {
              "field-type": {
                "basic": "shadcn-combobox"
              },
              "tooltip": null,
              "default": "ALL",
              "check": null,
              "field-rule": "computed -> Scopes (via: eventTitle.field), (display: scopeName):  Multivalued field"
            },
            "eventTitle": {
              "field-type": {
                "combobox": "shadcn-comboboxGroups"
              },
              "tooltip": null,
              "default": "ALL",
              "check": null,
              "field-rule": "FK -> Events (display: eventName): Multivalued field"
            },
            "customerTitle": {
              "field-type": {
                "combobox": "shadcn-combobox"
              },
              "tooltip": null,
              "default": "ALL",
              "check": null,
              "field-rule": "FK -> Customers (display: customerName): Multivalued field"
            }
          }
        }
      }
    },
    form: formFor(forecasts.entity, {
      fields: {
        "Business Unit": { attribute: "businessUnitID", tooltip: "Pick the unit first — the SLA options narrow to it (pre-RBAC filter input, issue #346)" },
        "SLA": { attribute: "slaID", widget: "selectgroups", tooltip: "The contract this forecast projects volume for — customer derives from it", check: requires("Business Unit"), rule: { list: true, groupBy: "customerName", filteredBy: "Business Unit" } },
        "Forecast Period": { attribute: "forecastPeriod" },
        "Period Start": { attribute: "periodStart", widget: "month", check: requires("Forecast Period") },
        "Status": { attribute: "status" },
      },
    }),
    cards: null,
    tableFilters: true,
    subitemTables: [
      "Forecast Scopes"
    ],
  }),
  table(forecastScopes, {
    visibility: "show",
    dashboardOrder: 4,
    reports: {
      "Report-A": {
        "graph_type": "stacked_bar",
        "rule": "forecastScopeID.estimatedHours grouped by productScopeID (scope name), stacked by roles",
        "filters": {
          "fields": {
            "periodFrame": {
              "field-type": {
                "range-picker": "shadcn-Date Picker"
              },
              "tooltip": null,
              "default": "last six months from current date",
              "check": null,
              "field-rule": null
            },
            "eventTitle": {
              "field-type": {
                "combobox": "shadcn-combobox"
              },
              "tooltip": null,
              "default": "ALL",
              "check": null,
              "field-rule": "FK -> Events (display: eventName): Multivalued field"
            },
            "customerTitle": {
              "field-type": {
                "combobox": "shadcn-combobox"
              },
              "tooltip": null,
              "default": "ALL",
              "check": null,
              "field-rule": "FK -> Customers (display: customerName): Multivalued field"
            }
          }
        }
      }
    },
    form: formFor(forecastScopes.entity, {
      fields: {
        "Business Unit": { attribute: "businessUnitID", tooltip: "Pick the unit first — the Forecast options narrow to it (pre-RBAC filter input, issue #346)" },
        "Forecast": { attribute: "forecastID", widget: "selectgroups", check: requires("Business Unit"), rule: { list: true, whereCurrentMonth: "periodFinish", filteredBy: "Business Unit" } },
        "Event": { attribute: "eventID", tooltip: "Events covered by the forecast's contract (SLA payloads)", check: requires("Forecast"), rule: { filteredBy: "Forecast" } },
        "Product Scope": { attribute: "productScopeID", widget: "selectgroups", tooltip: "Product scopes packaged by the contract's payloads for this event — scope and product group derive from it", check: requires("Event"), rule: { list: true, groupBy: "scopeName", filteredBy: "Event + Forecast" } },
        "Function": { attribute: "functionID", tooltip: "The function this demand line projects hours for", check: requires("Product Scope"), rule: { filteredBy: "Event" } },
        "Notes": { attribute: "notes", widget: {"key":"field","hint":"shadcn-Textarea"}, check: requires("Product Scope") },
        "Quantity": { attribute: "forecastScopeQuantity", widget: {"key":"input","hint":"shadcn-Input"}, check: requires("Product Scope") },
      },
    }),
    cards: null,
    tableFilters: true,
  }),
], {
  suppress: {
    "Forecasts.periodFinish": "#417: computed target \"add periodType month quantity to startDate to find periodFinish\" is not an entity (malformed rule?)",
    "Forecast Scopes.customerTitle": "#417: rollup target \"forecastID\" is not an entity",
    "Forecast Scopes.periodFrame": "#417: rollup target \"forecastID\" is not an entity",
    "Forecast Scopes.region": "#417: mirror target \"DISTINCT\" is not an entity"
  },
});
