/**
 * Operation module — authored in the spec (ADR-0002).
 *
 * Generated by `spec:scaffold-module Operation` from the hand-written
 * datamodel.json, then hand-maintained. Edit here and run `npm run build`;
 * never edit this module in the JSON (the CI drift guard rejects it).
 */
import { attr, computed, concat, defineModule, entity, enumOf, fk, mirror, rollup, table, userInput } from "../authoring.js";
import { requires, requiresValue } from "../behavior/check.js";
import { formFor } from "../view/form.js";

const tasks = entity("Tasks", "A Task is the application of an action to a process activity (workflow). It serves only as an execution template; concrete Jobs are created from Tasks in the Workspace module (where taskOwner, taskStatus, taskDueDate and projectID are set).", [
  attr("taskID", "INT", { notes: "Auto-generated primary key", constraints: ["PK"], show: [true, true] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "Form filter — narrows the Department options (pre-RBAC filter input, issue #344; the #340 chain applied to Tasks). Deliberately does NOT filter the Event select: 16/46 demo tasks chain events whose unit differs from their process department's unit — filtering Event by unit would orphan stored picks (session decision). Seeds: the department's unit (tools/migrate_task_prerbac_filters.py).", constraints: ["FK"], show: [false, false] }),
  attr("departmentID", "FK", { rel: fk("Departments", { display: "departmentName" }), notes: "Form filter — narrows the Process options together with the Event leg (pre-RBAC filter input, issue #344). Seeds: the process's departmentID (tools/migrate_task_prerbac_filters.py).", constraints: ["FK"], show: [false, false] }),
  attr("eventID", "FK", { rel: fk("Events", { display: "eventTitle" }), notes: "Event that triggered this task", constraints: ["FK","NOT NULL"], show: [true, true] }),
  attr("processID", "FK", { rel: fk("Processes", { display: "processName" }), notes: "Stored FK (materialize-FK convention) — the process of the selected event; the form filters the options by the Event field. The old \"rollup: from eventID\" prose made the parser resolve the TARGET as the Events table (fuzzy id-suffix match), so the Process select offered eventIDs (2026-08-04 bug).", constraints: ["NOT NULL"], show: [true, true] }),
  attr("workflowID", "VARCHAR", { rel: rollup("Workflows", "processID", { display: "activityName" }), notes: "Options filtered by matching processID", constraints: ["NOT NULL"], show: [true, true] }),
  attr("actionID", "VARCHAR", { rel: computed("Actions", { via: "activityID", display: "actionName" }), constraints: ["NOT NULL"], show: [true, true] }),
  attr("predecessorTask", "FK", { rel: fk("Tasks", { display: "taskName" }), notes: "Self-referential task ordering (issue #302; nullable — the first task of a process has no predecessor). Unlike Workflows there is NO constrain/indentationRule dimension: every task link is start-to-finish (sequential). The form select offers the tasks of the selected Process.", constraints: ["FK"] }),
  attr("taskIndentationID", "computed", { rel: {"kind":"taskorder","predField":"predecessorTask","stepField":"workflowID"}, notes: "Derived task outline number (1.0.1, 1.1.2, 2.0.1…) — never stored (issue #302): the workflow step's indentationID is the base, padded to two segments when it is a single major number (1 → 1.0 — the planned Gantt webhook consumers need a fixed depth), and the task's sequence within the SAME step (predecessorTask chain) appends as the last segment. A predecessor in ANOTHER step does not sub-number — the counter restarts per step (the issue's T04 example). Every Tasks subitem context orders by this value.", show: [true, true] }),
  attr("requirementName", "computed", { rel: rollup("Procedures", "taskID", { display: "requirementName" }), notes: "Derived — requirements of the task's procedures (doctrine: tasks are requirement-free, the procedure carries the requirement set; since issue #364 an empty procedure set covers nothing — the wildcard is retired)", show: [false, false] }),
  attr("functionID", "VARCHAR", { rel: computed("Competence", { via: "taskID", display: "functionName" }), notes: "multivalued — derived from the competences referencing this task", show: [false, false] }),
  attr("executionTime", "mirror", { rel: {"kind":"sum","childAttr":"procedureID","field":"executionTime","multiplierField":null}, notes: "Derived — procedures create the variance in task duration (Rafael, 04/08): the requirement set changes how long a task takes, so the time is registered PER PROCEDURE and the task shows the sum of its procedures.", show: [false, false] }),
  attr("competenceID", "VARCHAR", { rel: rollup("Competence", "taskID", { display: "competenceName" }), notes: "multivalued", show: [false, false] }),
  attr("userID", "mirror", { rel: {"kind":"certifiedusers","srcField":"taskID","display":"userName"}, notes: "multivalued — derived live (issue #214): People holding a CERTIFIED Onboarding (isCertified==true) on a task-compatible competence, whose combined competences cover ALL the requirements the task derives from its procedures (union of the requirement sets; a wildcard procedure covers everything) — the certified-responsible doctrine at the Tasks level. Authored 2026-08-19 as prose ('users that have the competences that matches all the requirements for the procedure applied to the task', constraint isCertified==true); normalized to the CERTIFIED-USERS rule kind (certifiedUsersForTask in resolve.js). Ticket context (issue #233): rendered inside a Ticket's Tasks tab, coverage must ALSO span the ticket's live inherited requirement set (#226) — the subitem accessor passes ticketRequirements(ticket) as extra ids; the standalone Tasks dashboard stays task-level. Procedure-status gate (sv71): a competence whose whole procedure group is non-Approved is INERT — it contributes no coverage until the method is Approved, and a non-Approved wildcard no longer certifies everything. RESTORED to the Ticket Tasks tab via its tab-columns entry (sv75, Rafael's ask) — the #299 global hide stays for every other context (subitem-display false).", displayName: "Users", show: [false, false] }),
  attr("procedureRegistry", "mirror", { rel: {"kind":"ticketprocedure","srcField":"taskID","display":"procedureRegistry"}, notes: "The single procedure the requirement context selects for the task (issue #270): inside a Ticket's Tasks tab the context is the ticket's live inherited requirement set (#226) — candidates are the task's procedures whose requirementID[] covers ALL the ticket requirements (AND semantics, not OR; since issue #364 an empty set covers only an empty context — the wildcard is retired, pre-sv98 snapshots keep the old reading). Since issue #332 the candidates are additionally scope-gated: a procedure must name at least one scope the ticket admits (an empty scope key names none since #364). Since the eligibility round (sv103) only APPROVED procedures are candidates — the sv71 'dispatch ungated' decision is superseded: a method awaiting approval cannot be the documented way to execute the task. Exactly one candidate renders its procedureRegistry as a pill tag; zero or several render GAP — and a REDUNDANCY (several eligible methods) carries the hover hint 'Procedures redundancy <ids>' naming the collision (ticketProcedureHint in resolve.js, cellHint in table.js). The subitem accessor passes ticketRequirements(ticket) and ticketAdmittedScopeIds(ticket) (mapSubitem in app.js, the #233 pattern); the standalone Tasks drawer falls back to the task-level set (unique procedure or GAP, no scope context — ungated). ticketProcedureForTask in resolve.js.", displayName: "Procedure", show: [false, true] }),
  attr("procedureExecutionTime", "mirror", { rel: {"kind":"ticketprocedure","srcField":"taskID","display":"executionTime"}, notes: "Execution time of the procedure the requirement context selects for the task (sv75, Rafael's ask — rides the #270 TICKET-PROCEDURE resolution with the display re-pointed to the procedure's executionTime): time lives PER PROCEDURE (2026-08-04 doctrine), so the ticket-contextual column shows the resolved method's time; zero or several candidates render GAP (caution pill; the value itself renders plain — only the registry column pills the resolved method). Shown only on the Ticket Tasks tab via tab-columns (subitem-display false — the #299 hide holds elsewhere); the standalone Tasks drawer falls back to the task-level set.", displayName: "Execution Time", show: [false, false] }),
  attr("roles", "FK", { rel: fk("Roles", { display: "roleName" }), notes: "multivalued — roles that may execute the task (#414: stored role ids were declared as a computed with a field as target)", constraints: ["FK"], show: [false, false] }),
  attr("parentStepID", "rollup", { rel: rollup("Workflows", "workflowID", { display: "actionName" }), show: [false, false] }),
  attr("procedureID", "rollup", { rel: rollup("Procedures", "taskID", { display: "procedureRegistry" }), notes: "Procedures registered for this task (subitem tab). Visible column since issue #271: a task with NO procedure is a gap — the empty rollup renders the GAP caution tag (gap-tag flag). Header overridden to the plural 'Procedures' (humanize would collide with the #270 'Procedure' column, the single ticket-context resolution). Kept out of the ticket Tasks tab (subitem-display false) — there the #270 column already carries the contextual GAP signal.", displayName: "Procedures", gapTag: true }),
  attr("ticketID", "rollup", { rel: rollup("Tickets", "taskID"), show: [false, false] }),
  attr("taskName", "VARCHAR", { rel: concat("activityName", {"lit":"-"}, "actionName"), show: [false, false] }),
  attr("taskOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c))", constraints: ["FK"], show: [false, false] }),
]);

const processes = entity("Processes", "The Process table groups workflows. The user creates a process item that is later used to build the process steps (workflow) records.", [
  attr("processID", "INT", { constraints: ["PK"], show: [false, false] }),
  attr("processSystemID", "VARCHAR", { notes: "Optional external registry system ID reference; not mandatory" }),
  attr("processName", "VARCHAR", { show: [true, true] }),
  attr("eventID", "FK", { rel: fk("Events", { display: "eventTitle" }), notes: "Event that triggered this Process", constraints: ["FK","NOT NULL"], show: [true, true] }),
  attr("processOwner", "FK", { rel: fk("People", { display: "userName" }), constraints: ["FK"], show: [true, true] }),
  attr("processDescription", "TEXT"),
  attr("parentProcessID", "FK", { rel: fk("Processes", { display: "processName" }), notes: "Self-referential 'Sub-process of' (nullable)", constraints: ["FK"] }),
  attr("departmentID", "FK", { rel: fk("Departments", { display: "departmentName" }), notes: "Department running the process — moved DOWN from Events (issue #159); options filtered by the event's business unit", constraints: ["FK"], show: [false, false] }),
  attr("productScopeID", "FK", { rel: fk("Product Scopes", { concat: [{"field":"productName"},{"lit":" | "},{"field":"scopeName"}] }), notes: "Multivalued — product scopes this process covers, offered from the selected event's applicability. The empty-list wildcard is RETIRED (issue #368): an undeclared list covers nothing — 'all' is every admitted scope explicitly selected (sv101 materialized the demo blanks with the event's admitted set; a scope packaged later requires revisiting the process).", constraints: ["FK"], show: [false, false] }),
  attr("squadID", "FK", { rel: fk("Squads", { display: "squadName" }), notes: "Squad running the process — offered from the squads of the process's own department (issue #159; was: the event's department)" }),
  attr("processStatus", "ENUM", { rel: enumOf("Active", "Draft", "Deprecated"), show: [true, true] }),
  attr("targetExecutionTime", "rollup", { rel: rollup("Tasks"), notes: "Average execution time across task groups sharing the same action + workflow combination", show: [false, false] }),
  attr("processVersion", "VARCHAR", { notes: "e.g., \"v1.2\"" }),
  attr("activities", "rollup", { rel: rollup("Workflows", "processID", { display: "activityName" }), notes: "Activities of this process, reached through its workflow steps", show: [false, false] }),
  attr("tasks", "rollup", { rel: rollup("Tasks", "processID"), notes: "All Tasks belonging to this Process", show: [false, false] }),
  attr("productName", "VARCHAR", { rel: {"kind":"mirror","target":"Tasks","via":null,"viaList":null,"display":"products","concat":null,"filter":null}, notes: "From tasks rollup, for report filtering" }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "Stored FK since issue #348 (materialize-FK convention — was a mirror of the EVENT's unit): the pre-RBAC filter input gating the Department select. Seeds: the DEPARTMENT's unit (tools/migrate_process_prerbac_filters.py — census: 2/6 demo processes chain events of another unit, PR2/PR5, so the event's unit cannot drive the user chain; the #344 posture — the Event select stays unfiltered).", constraints: ["FK"] }),
  attr("scopeName", "VARCHAR", { rel: {"kind":"mirror","target":"Tasks","via":null,"viaList":null,"display":"scopes","concat":null,"filter":null}, notes: "From tasks rollup, for report filtering" }),
]);

const activities = entity("Activities", "Hidden registry (dashboard-order 0) of the activities that form workflow steps (step = activity x process, v3-review D3). Created inline via the '+' button on the Workflows Activity select -- FK-keyed, no free text, so grouping/filtering never breaks on typos.", [
  attr("activityID", "INT", { constraints: ["PK"], show: [false, false] }),
  attr("activityName", "VARCHAR", { show: [true, true] }),
  attr("activityDescription", "TEXT", { notes: "nullable", show: [true, true] }),
  attr("actionID", "rollup", { rel: rollup("Tasks", "activityID", { display: "actionName" }), notes: "All actions derived from this Activity", show: [false, false] }),
  attr("activityOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c))", constraints: ["FK"], show: [false, false] }),
]);

const workflows = entity("Workflows", "Registry of the steps of each process. Through the relations of its records users understand how a process should be executed in terms of activities.", [
  attr("workflowID", "INT", { notes: "Displayed as e.g., \"WF-002\"", constraints: ["PK"], show: [true, true] }),
  attr("workflowName", "VARCHAR", { rel: concat("activityName", "processName"), notes: "Not a user input", show: [false, false] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "Form filter — narrows the Department options (pre-RBAC filter input, issue #342; the #340 Procedures chain applied to Workflows). Seeds: the department's unit (tools/migrate_workflow_prerbac_filters.py).", constraints: ["FK"], show: [false, false] }),
  attr("departmentID", "FK", { rel: fk("Departments", { display: "departmentName" }), notes: "Form filter — narrows the Process options (pre-RBAC filter input, issue #342). Seeds: the process's departmentID (tools/migrate_workflow_prerbac_filters.py).", constraints: ["FK"], show: [false, false] }),
  attr("processID", "FK", { rel: fk("Processes", { display: "processName" }), notes: "The form combobox is gated on Department and offers only the selected department's processes (issue #342 — generic stored-key cascade on Processes.departmentID)", constraints: ["FK","NOT NULL"] }),
  attr("activityID", "FK", { rel: fk("Activities", { display: "activityName" }), notes: "The activity this step executes (step = activity × process); stored FK since v3-review R5 — was a dead rollup", constraints: ["FK","NOT NULL"], show: [true, true] }),
  attr("parentStepID", "FK", { rel: fk("Workflows", { display: "activityName" }), notes: "Self-referential step ordering (nullable — first step of a process has no parent). Displays the step's ACTIVITY name (Rafael, 04/08), resolved through the step's activityID.", constraints: ["FK"], show: [true, true] }),
  attr("indentationRule", "VARCHAR", { rel: enumOf("start-to-finish", "start-to-start", "finish-to-start", "finish-to-finish"), notes: "(nullable)", show: [true, true] }),
  attr("indentationID", "computed", { rel: {"kind":"steporder","parentField":"parentStepID","ruleField":"indentationRule","groupField":"processID"}, notes: "Derived outline number (1, 2, 2.1, 3…) — never stored; computed per process from the parent-step chain. Sequential rules (start-to-finish, finish-to-start) take the next major number, parallel rules (finish-to-finish, start-to-start) sub-number under the parent. See identation-rule.md.", show: [true, true] }),
  attr("taskID", "rollup", { rel: rollup("Tasks"), notes: "Tasks that use this workflow item", show: [false, false] }),
  attr("inputs", "VARCHAR", { rel: {"kind":"mirror","target":"Tasks","via":null,"viaList":null,"display":"taskInput","concat":null,"filter":null}, notes: "Determined by taskID" }),
  attr("outputs", "VARCHAR", { rel: {"kind":"mirror","target":"Tasks","via":null,"viaList":null,"display":"taskOutput","concat":null,"filter":null}, notes: "Determined by taskID" }),
]);

const actions = entity("Actions", "An action defines the procedure to be performed to execute a given step (workflow) within a process.", [
  attr("actionID", "INT", { constraints: ["PK"], show: [false, false] }),
  attr("actionName", "VARCHAR", { show: [true, true] }),
  attr("actionDescription", "TEXT", { show: [true, true] }),
  attr("taskID", "rollup", { rel: rollup("Tasks", "actionID"), notes: "Tasks that use this action", show: [false, false] }),
  attr("activityID", "VARCHAR", { rel: {"kind":"mirror","target":"Tasks","via":null,"viaList":null,"display":"activityName","concat":null,"filter":null}, notes: "From taskID rollup; allows filtering by activity", show: [false, false] }),
  attr("workflowID", "VARCHAR", { rel: {"kind":"mirror","target":"Tasks","via":null,"viaList":null,"display":"workflowID","concat":null,"filter":null}, notes: "From taskID rollup; allows filtering by workflow (activity + process)", show: [false, false] }),
  attr("actionOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c))", constraints: ["FK"], show: [false, false] }),
]);

const handouts = entity("Handouts", "Input or output document/deliverable exchanged between process steps (ISO §4.4.2(b) — retained documented information).", [
  attr("handoutID", "INT", { constraints: ["PK"], show: [false, false] }),
  attr("handoutName", "VARCHAR", { show: [true, true] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "Single-valued — pre-RBAC filter input (issue #340): gates and filters the Departments multicheck. Seeds: the unit of the handout's first using department (tools/migrate_prerbac_procedure_filters.py).", constraints: ["FK"] }),
  attr("departmentID", "FK", { rel: fk("Departments", { display: "departmentName" }), notes: "multivalued — departments this handout serves (issue #340): the Procedures Inputs/Outputs pickers narrow to handouts naming the selected department. The empty-list wildcard is RETIRED (issue #368): an undeclared list is offered NOWHERE — 'everywhere' is every department explicitly selected (pre-sv101 snapshots keep the Q1 reading). Seeds: union of the departments of the procedures using the handout as input or output, procedure row order. A handout whose departments span units carries the accepted #290 edit-time narrowing trap (the unit-filtered multicheck drops other-unit picks on save).", constraints: ["FK"] }),
  attr("handoutDescription", "TEXT", { notes: "nullable" }),
  attr("createdAt", "DATETIME", { show: [false, false] }),
  attr("channelID", "FK", { rel: fk("Channels", { display: "channelName" }), notes: "Delivery channel", constraints: ["FK"], show: [true, true] }),
  attr("taskID", "rollup", { rel: rollup("Tasks"), notes: "All tasks that use this handout as input or output", show: [false, false] }),
  attr("processID", "mirror", { rel: {"kind":"mirror","target":"Tasks","via":null,"viaList":null,"display":"processID","concat":null,"filter":null}, notes: "Chain inherited from the task(s) referencing this handout", show: [false, false] }),
  attr("workflowID", "mirror", { rel: {"kind":"mirror","target":"Tasks","via":null,"viaList":null,"display":"workflowID","concat":null,"filter":null}, notes: "Chain inherited from the task(s) referencing this handout", show: [false, false] }),
  attr("actionID", "mirror", { rel: {"kind":"mirror","target":"Tasks","via":null,"viaList":null,"display":"actionID","concat":null,"filter":null}, notes: "Chain inherited from the task(s) referencing this handout", show: [false, false] }),
  attr("templateName", "VARCHAR", { notes: "nullable" }),
  attr("templateURL", "LINK", { notes: "nullable", show: [true, true] }),
]);

const channels = entity("Channels", "Communication or delivery channel used in process steps, with assigned owner (ISO §7.4).", [
  attr("channelID", "INT", { constraints: ["PK"], show: [false, false] }),
  attr("channelName", "VARCHAR", { notes: "e.g., Portal, Salesforce, Outlook", show: [true, true] }),
  attr("channelOwner", "email", { notes: "Company or person responsible for managing the channel" }),
  attr("channelStatus", "ENUM", { rel: enumOf("Active", "Inactive"), show: [true, true] }),
  attr("handouts", "rollup", { rel: rollup("Handouts", "channelID"), notes: "All Handouts delivered through this channel", show: [false, false] }),
]);

const procedures = entity("Procedures", "Documented method for executing a Task (ISO 9001:2015 §4.4 operations chain; §7.5 documented information). Tasks stay requirement-free — the procedure is where requirements bite: each row registers how a task is performed under a given requirement set, with its own input/output handouts. The requirement set is an explicit selection (issue #364): the procedure covers exactly the requirements listed — an empty list covers none, and a requirement registered later requires revisiting each procedure.", [
  attr("procedureID", "INT", { notes: "Auto-generated primary key", constraints: ["PK"], show: [false, false] }),
  attr("procedureRegistry", "VARCHAR", { notes: "External registry number / unique identification (label attribute)", constraints: ["NOT NULL"], show: [true, true] }),
  attr("processID", "FK", { rel: fk("Processes", { display: "processName" }), notes: "Form filter — narrows the Task options", constraints: ["FK"] }),
  attr("taskID", "FK", { rel: fk("Tasks", { display: "taskName" }), notes: "Task this procedure executes — join anchor for the Tasks → Procedures subitem tab", constraints: ["FK","NOT NULL"] }),
  attr("procedureURL", "LINK", { notes: "Link to the procedure documentation", show: [true, true] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "Form filter — narrows the Department options (pre-RBAC filter input, issue #340). Demo seeds re-keyed by tools/migrate_prerbac_procedure_filters.py to the department's unit (the pre-#340 rows all carried BU01 while their processes' departments spanned four units — the #281 edit-integrity posture).", constraints: ["FK"], show: [false, false] }),
  attr("departmentID", "FK", { rel: fk("Departments", { display: "departmentName" }), notes: "Form filter — narrows the Process options (pre-RBAC filter input, issue #340; the #159 drop is superseded for the FORM chain — Competence keeps deriving its department via the process). Seeds: the process's departmentID (tools/migrate_prerbac_procedure_filters.py).", constraints: ["FK"], show: [false, false] }),
  attr("branchID", "FK", { rel: fk("Branches", { display: "branchName" }), notes: "multivalued — branches this procedure applies to (issue #353, wizard step Application). The empty-set wildcard is RETIRED (issue #364): applicability is an explicit pick — 'apply to all' means every value selected (today's list; a branch registered later requires revisiting the procedure), empty = applies to nothing. Options = branches of the selected Unit's customers (branchesForUnits in forms.js, two-hop via Branches.customerID). Still DECLARED only — the ticket→procedure match does NOT gate on it yet (#332 posture: gating comes in its own round with a flip census). Materialized from the pre-#364 wildcard seeds by migrate_no_wildcards.py.", constraints: ["FK"], show: [false, false] }),
  attr("customerID", "FK", { rel: fk("Customers", { display: "customerName" }), notes: "multivalued — customers this procedure applies to (issue #353, wizard step Application). The empty-set wildcard is RETIRED (issue #364): explicit pick, empty = applies to nothing. Options = the Unit's customers narrowed to the selected Branches' registrations (customersForUnitBranches in forms.js). Declared-only — no match gate yet (same session decision as branchID). Materialized from the pre-#364 wildcard seeds by migrate_no_wildcards.py.", constraints: ["FK"], show: [false, false] }),
  attr("productScopeID", "FK", { rel: fk("Product Scopes", { concat: [{"field":"productName"},{"lit":" | "},{"field":"scopeName"}] }), notes: "Multivalued — product scopes this procedure applies to, offered from the selected process's list. The empty-set wildcard is RETIRED (issue #364): explicit pick, empty = names no scope (legacy pre-sv98 snapshots keep the Q1 reading via legacyWildcardData). Since issue #332 the key GATES the ticket→procedure match directly (ticketProcedureForTask in resolve.js): with a ticket scope context, a procedure pinned to scopes must name at least one scope the ticket admits (ticketAdmittedScopeIds — the payload-chain set ∩ the ticket's chosen scope) or it is no candidate; the task-level fallback (standalone Tasks drawer, no ticket context) is ungated. Demo seeds re-aligned by tools/migrate_procedure_scope_gate.py (stored picks ∪ the task→process→event payload-packaged scopes — the #281 edit-integrity posture: every pre-gate dispatch survives).", constraints: ["FK"], show: [false, false] }),
  attr("requirementID", "FK", { rel: fk("Requirements", { display: "requirementName" }), notes: "Multivalued; nullable — requirements under which this procedure applies. The empty-set wildcard is RETIRED (issue #364): 'apply to all' = every requirement explicitly selected (a requirement registered later requires revisiting each procedure — the deliberate quality review the dynamic wildcard bypassed); empty = covers only an empty context. Legacy pre-sv98 snapshots keep the Q1 reading (legacyWildcardData). Form options are the UNIT-WIDE universe (issue #304, replacing the #159 product-scope/task narrowing): every Active requirement whose unit key is empty (Q1) or names the selected unit AND whose region key is empty or names one of the unit's served regions (Business Units.regionID — the #230 posture; requirementsForUnit in forms.js). The quality manager picks the combination here — the procedure is the requirement decision point (#231).", constraints: ["FK"], show: [true, true] }),
  attr("taskInput", "FK", { rel: fk("Handouts", { display: "handoutName" }), notes: "Multivalued — input handouts of this procedure (moved from Tasks — iterations round A5); form options follow the owning chain (unlinked handouts always offered)", constraints: ["FK"], show: [false, false] }),
  attr("customerInputID", "FK", { rel: fk("Handouts", { display: "handoutName" }), notes: "multivalued — the inputs of THIS procedure the customer must provide upon ticket creation (issue #324, replacing the handout-level customerFlag #280: the decision is contextual to the procedure — the same handout may be a customer input in one method and internal in another). Subset of taskInput: the form multicheck offers exactly the chosen Inputs (customerInputsForSelection in forms.js) and the rebuild drops picks whose input was removed (form-integrity working FOR us). EMPTY = no customer inputs — deliberate no-Q1 (#280 posture: an inputless ticket is legitimate). Feeds the Tickets Inputs tab (TICKET-INPUTS in resolve.js; pre-sv77 snapshots without this key fall back to the legacy handout flag).", constraints: ["FK"], show: [false, false] }),
  attr("taskOutput", "FK", { rel: fk("Handouts", { display: "handoutName" }), notes: "Multivalued — output handouts of this procedure (moved from Tasks — iterations round A5); form options follow the owning chain (unlinked handouts always offered)", constraints: ["FK"], show: [false, false] }),
  attr("executionTime", "DECIMAL", { notes: "Hours to execute the task under THIS procedure's requirement set — moved from Tasks (2026-08-04): procedures create the variance in task duration", show: [true, true] }),
  attr("userID", "mirror", { rel: {"kind":"certifiedusers","srcField":"procedureID","display":"userName"}, notes: "multivalued — derived live (issue #271): People holding a CERTIFIED Onboarding (isCertified==true) on a competence bound to THIS procedure (Competence.procedureID, 1:1 since #231). Strict association, no wildcard: a competence without a procedure widens staffing coverage but does not staff a specific procedure's Users column. A procedure NO ONE is certified to execute is a gap the system must point at — the empty value renders the GAP caution tag (gap-tag flag, derivedValue wrapper in resolve.js). Downstream (#270): once the ticket context narrows a task to its single procedure, that procedure already carries — or lacks — its eligible users. certifiedUsersForProcedure in resolve.js; the srcField (procedureID vs taskID) picks the chain inside the shared CERTIFIED-USERS rule kind. Procedure-status gate (sv71): a non-Approved procedure has NO eligible users yet — the column shows the GAP until the status flips to Approved.", displayName: "Users", gapTag: true, show: [true, true] }),
  attr("procedureOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §7.5) — iterations round A6", constraints: ["FK"] }),
  attr("procedureStatus", "ENUM", { rel: enumOf("Approved", "In Progress", "To Do"), notes: "Lifecycle of the documented method (authored 2026-09-03, absorbed with issue #302; spelling normalized to the house ENUM-type + enum-rule convention). ELIGIBILITY GATE since the procedure-status round (sv71): only an Approved procedure can be exercised — certified onboardings on competences bound to a non-Approved procedure do not make the holder eligible (certifiedUsersForTask / certifiedUsersForProcedure / certified-responsible all gate through procedureApproved / competenceExercisable in resolve.js; rows without the key count as Approved, legacy tolerance). Demo SOPs seed Approved — they staff competences and drive execution times, an unapproved status would be dishonest.", show: [true, true] }),
]);

const requirements = entity("Requirements", "Requirements applicable to scopes and product groups — regulatory, clinical/design and commercial obligations any service department can register and reuse (ISO 9001:2015 §4.3, §8.2).", [
  attr("requirementID", "INT", { constraints: ["PK"], show: [false, false] }),
  attr("requirementName", "VARCHAR", { show: [true, true] }),
  attr("requirementDescription", "TEXT", { show: [true, true] }),
  attr("regionID", "FK", { rel: fk("Regions", { display: "regionName" }), notes: "multivalued — regions this requirement applies to. Doctrine refined at sv106 (Rafael): a DECLARED dimension constrains, an undeclared one does not — leave the key empty to not constrain by region (the sv99 strict reading was reverted; the #364 no-wildcard doctrine stays on the coverage sets)", constraints: ["FK"] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "multivalued — business units this requirement APPLIES to (the inheritance dimension): a DECLARED key constrains, an undeclared one does not (sv106). NULLABLE again since sv107 — the #359 mandate mixed the pre-RBAC filter role into this key and made every requirement unit-constrained; the filter role moved to registryUnitID (Rafael's split: Registry unit filters the wizard options, this key optionally declares unit applicability — the Applicability multicheck offers exactly the Registry unit). Demo rows keep the #359 all-units seed (≡ unconstrained under declared-constrains — zero flips). Constraints picker on Tickets: declared = only its units, blank = every unit (sv106 posture)", constraints: ["FK"], show: [false, false] }),
  attr("registryUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "Form filter — the pre-RBAC Registry unit (sv107, Rafael's split of the #359 role mixing): NOT NULL, picked on the wizard Registry step, its ONLY job is narrowing the Applicability options (regions = the unit's served regions; branches/customers/scopes/product groups/product scopes filtered by it; the applicability businessUnitID multicheck offers exactly this unit). NEVER read by the inheritance chains — a pure #334 filter input, removal candidate when RBAC lands. Seeds: first unit of the row's businessUnitID key (migrate_requirement_registry_unit.py)", constraints: ["FK","NOT NULL"], show: [false, false] }),
  attr("requirementTypeID", "FK", { rel: fk("Requirement Type", { display: "requirementTypeName" }), notes: "Type registry lives in the hidden Requirement Type table (dashboard-order 0)", constraints: ["FK"], show: [true, true] }),
  attr("ticketSelectable", "BOOLEAN", { notes: "Selectable on Tickets (issue #359, REDEFINED 2026-09-08; deliberate-selection since sv109): Yes makes this requirement an offerable CONSTRAINT on the Tickets wizard Request step — and once a ticket picks ≥1 constraint, being offered-but-unpicked EXCLUDES it from that ticket's inheritance (zero picks = no decision) for tickets of the SAME business unit (constraintsForTicketUnit in forms.js) — the picked constraints NARROW the ticket's Product Scope options to the scopes whose PS-REQUIREMENTS set covers them (AND). Pure filter: the inheritance chain is untouched either way (the #359 manual-union application was retired in the same redefinition). BOOLEAN-select convention (issue #218), default No. Demo cohort unchanged: customer-or-region-pinned rows seed Yes", show: [false, false] }),
  attr("branchID", "FK", { rel: fk("Branches", { display: "branchName" }), notes: "multivalued — branches this requirement applies to; a DECLARED key constrains, an undeclared one does not (sv106 refinement — a requirement defined only for a branch binds every ticket related to it). ACTIVE dimension since issue #353: matchRequirements gates ticket inheritance on the ticket's OUTPUT branch — the stored Tickets.branchID chosen below the Applicant (sv108, Rafael's conceptual fix; supersedes the sv105/sv106 party-branch union: a branch-pinned requirement applies exactly to the branch receiving the ticket's output; blank input skips the dimension — lenient posture), the Forecast Scopes rollup carries the forecastID.slaID.branchID leg, and the Procedures wizard facets the requirement options by it (Branches Requirements facet — a full-dimension set buckets as global, #366 display posture). Form multicheck since #366.", constraints: ["FK"], show: [true, true] }),
  attr("customerID", "FK", { rel: fk("Customers", { display: "customerName" }), notes: "multivalued since issue #366 (was single, #180) — customers this requirement applies to; a DECLARED key constrains, an undeclared one does not (sv106 refinement). Unit-gated form multicheck, options = the selected units' customers grouped by unit (#212 cascade kept)", constraints: ["FK"], show: [false, false] }),
  attr("scopeID", "FK", { rel: fk("Scopes", { display: "scopeName" }), notes: "multivalued — scopes this requirement applies to; a DECLARED key constrains, an undeclared one does not (sv106 refinement — a requirement defined only for a scope binds every ticket whose admitted product scopes carry it)", constraints: ["FK"], show: [true, true] }),
  attr("productGroupID", "FK", { rel: fk("Product Groups", { concat: [{"field":"productName"},{"lit":" | "},{"field":"specsSummary"}] }), notes: "multivalued — product groups this requirement applies to; a DECLARED key constrains, an undeclared one does not (sv106 refinement)", constraints: ["FK"], show: [true, true] }),
  attr("productScopeID", "FK", { rel: fk("Product Scopes", { display: "productScopeRegistry" }), notes: "multivalued — product scopes this requirement applies to DIRECTLY (issue #294, inverting the #288 form-level link: the requirement declares its combinations, the Product Scope form no longer picks requirements; picker shows the productScopeRegistry code, issue #296). A DECLARED key constrains, an undeclared one does not (sv106 refinement); a PROPER SUBSET narrows inheritance to the named scopes, and the PS-REQUIREMENTS named leg reads a full-dimension set as global — not a specific pin (namesFullDimension, the #288 globals-stay-out display preserved)", constraints: ["FK"], show: [false, false] }),
  attr("requirementTitle", "mirror", { rel: concat("requirementName", {"lit":"-"}, "requirementTypeName"), show: [true, true] }),
  attr("isActive", "ENUM", { rel: enumOf("Active", "Inactive"), show: [true, true] }),
  attr("regulatoryReference", "VARCHAR", { notes: "e.g., IEC standard code (nullable)", show: [true, true] }),
  attr("regulatoryURL", "LINK"),
]);

const requirementType = entity("Requirement Type", "Registry of requirement types selectable when creating a Requirement (created inline via the \"+\" on the Type select).", [
  attr("requirementTypeID", "INT", { notes: "Auto-generated primary key", constraints: ["PK"], show: [false, false] }),
  attr("requirementTypeName", "VARCHAR", { show: [true, true] }),
  attr("requirementTypeDescription", "TEXT"),
  attr("requirementTypeOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c))", constraints: ["FK"], show: [false, false] }),
]);

export const operation = defineModule("Operation", 5, [
  table(tasks, {
    visibility: "show",
    dashboardOrder: 1,
    reports: {
      "Report-A": {
        "graph_type": "bar",
        "rule": "Count of Tasks grouped by processID",
        "filters": null
      },
      "Report-B": {
        "overview-display": true,
        "graph_type": "bar",
        "rule": "Count of Tasks grouped by functionName",
        "filters": null
      }
    },
    form: formFor(tasks.entity, {
      fields: {
        "Business Unit": { attribute: "businessUnitID", tooltip: "Pick the unit first — the Department options narrow to it (pre-RBAC filter input, issue #344)" },
        "Department": { attribute: "departmentID", tooltip: "Pick the department — the Process options narrow to it (pre-RBAC filter input, issue #344)", check: requires("Business Unit"), rule: { filteredBy: "Business Unit" } },
        "Event": { attribute: "eventID", widget: "combobox" },
        "Process": { attribute: "processID", tooltip: "Processes of the selected Event and Department", check: requires("Event"), rule: { filteredBy: "Event + Department" } },
        "Activity": { attribute: "workflowID", check: requires("Process"), rule: { filteredBy: "process" } },
        "Action": { attribute: "actionID", check: requires("Activity") },
        "Predecessor Task": { attribute: "predecessorTask", tooltip: "Task of the SAME process executed before this one — the task outline number (taskIndentationID) derives from the workflow step and this chain. Leave empty for the first task; every task link is start-to-finish (issue #302).", check: requires("Process"), rule: { filteredBy: "Process" } },
      },
    }),
    cards: [
      {
        "Card 1-1": {
          "title": "Recurrent Actions across Processes",
          "card-rules": {
            "main-data": "Top 3 actions that appear in multiple processes",
            "trend-data": null,
            "detail-data": "this card must be a list with two columns: actionName | process count"
          },
          "card-component": "shadcn-card",
          "card-tooltip": "Most recurring actions across the process landscape, indicating key operational dependencies. Redefined from task-name recurrence (issue #216, option B): taskName derives activityName-actionName since issue #214 and no honest task name spans two processes in the demo data — the action dimension answers the same dependency question."
        }
      }
    ],
    tableFilters: true,
    subitemTables: [
      {
        "tab-order": 1,
        "rule": null,
        "tab-name": "Procedures",
        "tab-table": "Procedures"
      }
    ],
  }),
  table(processes, {
    visibility: "show",
    dashboardOrder: 3,
    reports: {
      "Report-A": {
        "graph_type": "bar",
        "rule": "Count of Tasks grouped by processName",
        "filters": [
          "productName",
          "scopeName"
        ]
      },
      "Report-B": null
    },
    form: formFor(processes.entity, {
      fields: {
        "Registry Number": { attribute: "processSystemID", tooltip: "Business Unit register number" },
        "Process Name": { attribute: "processName" },
        "Description": { attribute: "processDescription", tooltip: "Give a description for the process" },
        "Business Unit": { attribute: "businessUnitID", tooltip: "Pick the unit first — the Department options narrow to it (pre-RBAC filter input, issue #348)" },
        "Department": { attribute: "departmentID", tooltip: "Departments of the selected Business Unit", check: requires("Business Unit"), rule: { filteredBy: "Business Unit" } },
        "Event": { attribute: "eventID", widget: "combobox", tooltip: "The event that triggers the process" },
        "Product Scopes": { attribute: "productScopeID", tooltip: "Product scopes covered by this process — offered from the event's applicability; select every scope to cover all of today's list (issue #368; an empty list covers nothing)", check: requires("Event"), rule: { list: true, multi: true, filteredBy: "eventID" } },
        "Owner": { attribute: "processOwner", widget: "selectgroups", rule: { groupBy: "functionName", filteredBy: "Business Unit" } },
        "Status": { attribute: "processStatus" },
        "Process Version": { attribute: "processVersion", widget: {"key":"input","hint":"shadcn-input-email"} },
        "Squad": { attribute: "squadID", tooltip: "Squads of the process's department", check: requires("Department"), rule: { filteredBy: "departmentID" } },
      },
    }),
    cards: null,
    tableFilters: true,
    subitemTables: [
      "Workflows: ordered by indentationID"
    ],
  }),
  table(activities, {
    visibility: "show",
    dashboardOrder: 0,
    reports: null,
    form: formFor(activities.entity, {
      fields: {
        "Activity Name": { attribute: "activityName" },
        "Description": { attribute: "activityDescription", tooltip: "Give a description for the Activity" },
      },
    }),
    cards: null,
    tableFilters: true,
    subitemTables: [
      "Actions: rollup via Tasks.activityID"
    ],
  }),
  table(workflows, {
    visibility: "show",
    dashboardOrder: 5,
    reports: null,
    form: formFor(workflows.entity, {
      fields: {
        "Business Unit": { attribute: "businessUnitID", tooltip: "Pick the unit first — the Department options narrow to it (pre-RBAC filter input, issue #342)" },
        "Department": { attribute: "departmentID", tooltip: "Pick the department — the Process options narrow to it (pre-RBAC filter input, issue #342)", check: requires("Business Unit"), rule: { filteredBy: "Business Unit" } },
        "Process": { attribute: "processID", widget: "combobox", tooltip: "Processes of the selected Department", check: requires("Department"), rule: { filteredBy: "Department" } },
        "Activity": { attribute: "activityID", widget: "combobox", check: requires("Process") },
        "Parent Step": { attribute: "parentStepID", widget: "combobox", tooltip: "Previous step of the SAME process that feeds this one — options are the steps already registered for the selected process. Leave empty for the first step (it takes the next major number; steps with a parent sub-number under it).", check: requires("Process"), rule: { filteredBy: "Process", note: "display workflowID.activityName" } },
        "Indentation Rule": { attribute: "indentationRule", tooltip: "Dependency on the parent step: sequential rules (start-to-finish, finish-to-start) place this step after the parent; parallel rules (finish-to-finish, start-to-start) nest it under the parent. The step number (indentationID) is derived automatically.", check: requires("Parent Step") },
      },
    }),
    cards: [],
    tableFilters: true,
    subitemTables: [
      "Tasks: ordered by taskIndentationID"
    ],
  }),
  table(actions, {
    visibility: "show",
    dashboardOrder: 0,
    reports: null,
    form: formFor(actions.entity, {
      fields: {
        "Action Name": { attribute: "actionName" },
        "Description": { attribute: "actionDescription", check: requires("Action Name") },
      },
      subitemTables: [
        "Activities: via taskID"
      ],
    }),
    cards: [],
    tableFilters: true,
  }),
  table(handouts, {
    visibility: "show",
    dashboardOrder: 8,
    reports: null,
    form: formFor(handouts.entity, {
      fields: {
        "Name": { attribute: "handoutName" },
        "Description": { attribute: "handoutDescription" },
        "Business Unit": { attribute: "businessUnitID", tooltip: "Pick the unit first — the Departments options narrow to it (pre-RBAC filter input, issue #340)" },
        "Departments": { attribute: "departmentID", widget: "selectgroups", tooltip: "Departments this handout serves — the Procedures Inputs/Outputs pickers narrow to them; select every department to offer it everywhere (issue #368; an empty list offers it nowhere)", check: requires("Business Unit"), rule: { list: true, multi: true, filteredBy: "Business Unit" } },
        "Channel": { attribute: "channelID", widget: "combobox", tooltip: "Tool, app or system used to store or manage the handout" },
        "Template ID": { attribute: "templateName", tooltip: "Unique Identifier for the template" },
        "Template URL": { attribute: "templateURL", tooltip: "Acess Link for the template", check: requires("Template ID") },
      },
    }),
    cards: [],
    tableFilters: true,
  }),
  table(channels, {
    visibility: "show",
    dashboardOrder: 0,
    reports: null,
    form: formFor(channels.entity, {
      fields: {
        "Name": { attribute: "channelName" },
        "Owner": { attribute: "channelOwner" },
        "Status": { attribute: "channelStatus", rule: { enum: ["Active","Inactive"] } },
      },
    }),
    cards: [],
    tableFilters: true,
  }),
  table(procedures, {
    visibility: "show",
    dashboardOrder: 9,
    reports: null,
    form: formFor(procedures.entity, {
      steps: {
        "Registry": {
          "order": 1,
          "description": null
        },
        "Application": {
          "order": 2,
          "description": "Where this procedure applies — select every value to apply to all of today's list (issue #364: a new item requires revisiting the procedure)"
        },
        "Constraints": {
          "order": 3,
          "description": "Requirements this procedure answers for, faceted by what pins them"
        },
        "Inputs & Outputs": {
          "order": 4,
          "description": null
        }
      },
      fields: {
        "Registry Code": { attribute: "procedureRegistry", tooltip: "Registry number or unique identification for the procedure", step: "Registry" },
        "Unit": { attribute: "businessUnitID", step: "Registry" },
        "Department": { attribute: "departmentID", tooltip: "Pick the department — the Process options narrow to it (pre-RBAC filter input, issue #340)", step: "Registry", check: requires("Unit"), rule: { filteredBy: "Unit" } },
        "Process": { attribute: "processID", tooltip: "Processes of the selected Department", step: "Registry", check: requires("Department"), rule: { filteredBy: "Department" } },
        "Task": { attribute: "taskID", step: "Registry", check: requires("Process"), rule: { filteredBy: "Process" } },
        "Owner": { attribute: "procedureOwner", step: "Registry" },
        "Status": { attribute: "procedureStatus", step: "Registry" },
        "Procedure URL": { attribute: "procedureURL", tooltip: "Link to access the procedure documentation", step: "Registry", check: requires("Task") },
        "Execution Time": { attribute: "executionTime", tooltip: "Hours to execute the task under this procedure's requirement set", step: "Registry", check: requires("Task") },
        "Branches": { attribute: "branchID", tooltip: "Branches this procedure applies to (issue #353) — offered from the Unit's customers' branches; select every branch to apply to all of today's list (issue #364 — a branch registered later requires revisiting the procedure)", step: "Application", check: requires("Unit"), rule: { list: true, multi: true, filteredBy: "Unit" } },
        "Customers": { attribute: "customerID", tooltip: "Customers this procedure applies to (issue #353) — the Unit's customers, narrowed to the selected Branches' registrations; select every customer to apply to all of today's list (issue #364)", step: "Application", check: requires("Unit"), rule: { list: true, multi: true, filteredBy: "Unit + Branches" } },
        "Product Scopes": { attribute: "productScopeID", tooltip: "Product scopes this procedure applies to — offered from the process's packaged list (the issue #353 mockup narrows by Unit and Department; that filter awaits the Product Scope ↔ Department link, issue #352 — a unit filter today would orphan 96/264 stored picks and flip the #332 gate). Select every scope to apply to all of today's list (issue #364)", step: "Application", check: requires("Process"), rule: { list: true, multi: true, filteredBy: "processID" } },
        "Requirements": { attribute: "requirementID", widget: "selectgroups", tooltip: "Requirements under which this procedure applies — the Unit-wide universe (issue #304), faceted by what pins each requirement (issue #353): Product Scopes / Customers / Branches / Business Unit, most-specific facet wins. Customer facet narrows to the selected Branches' customers. Select every requirement to apply to all of today's list (issue #364 — a requirement registered later requires revisiting each procedure; an empty set covers nothing)", step: "Constraints", check: requires("Task"), rule: { list: true, multi: true, filteredBy: "Unit + Branches" } },
        "Inputs": { attribute: "taskInput", widget: "combobox", tooltip: "Handouts admitted for the selected Department (issue #353 — the department carries the unit transitively; a handout with no department is offered everywhere)", step: "Inputs & Outputs", rule: { multi: true, filteredBy: "Department" } },
        "Customer Inputs": { attribute: "customerInputID", widget: "combobox", tooltip: "Select which of the chosen Inputs must be provided by the customer upon ticket creation — the decision is made here, per procedure (issue #324); tick each customer-provided input explicitly (issue #364)", step: "Inputs & Outputs", check: requires("Inputs"), rule: { multi: true, filteredBy: "Inputs" } },
        "Outputs": { attribute: "taskOutput", widget: "combobox", tooltip: "Handouts admitted for the selected Department (issue #353 — the department carries the unit transitively; a handout with no department is offered everywhere)", step: "Inputs & Outputs", rule: { multi: true, filteredBy: "Department" } },
      },
    }),
    cards: null,
    tableFilters: true,
    subitemTables: [
      {
        "tab-order": 1,
        "rule": "(grouped by inputs)",
        "tab-name": "inputs",
        "tab-table": "Handouts"
      },
      {
        "tab-order": 2,
        "rule": "(grouped by outputs)",
        "tab-name": "outputs",
        "tab-table": "Handouts"
      },
      {
        "tab-order": 3,
        "rule": "(via: productScopeID)",
        "tab-name": "product scopes",
        "tab-table": "Product Scopes"
      }
    ],
  }),
  table(requirements, {
    visibility: "show",
    dashboardOrder: 2,
    reports: null,
    form: formFor(requirements.entity, {
      steps: {
        "Registry": {
          "order": 1,
          "description": null
        },
        "Applicability": {
          "order": 2,
          "description": "Where this requirement applies — the dimensions you DECLARE constrain the inheritance; a dimension left empty does not constrain (sv106: a requirement defined only for a branch binds every ticket related to that branch)"
        },
        "Compliance": {
          "order": 3,
          "description": "The external norm behind it and the lifecycle flag"
        }
      },
      fields: {
        "Name": { attribute: "requirementName", step: "Registry" },
        "Description": { attribute: "requirementDescription", step: "Registry" },
        "Type": { attribute: "requirementTypeID", step: "Registry" },
        "Business Unit": { attribute: "registryUnitID", tooltip: "The unit you are registering this requirement under (pre-RBAC filter, sv107) — it narrows every Applicability option and does NOT constrain the inheritance; declare unit applicability on the next step if intended", step: "Registry" },
        "Selectable on Tickets": { attribute: "ticketSelectable", tooltip: "Yes = this requirement becomes an offerable CONSTRAINT on the Tickets form for its business unit(s), used to filter the ticket's Product Scope options (issue #359 redefined) — the automatic inheritance is not affected either way", step: "Registry", rule: { default: "No" } },
        "Region": { attribute: "regionID", tooltip: "Regions this requirement applies to — offered from the Registry unit's served regions (a unit can exist in several regions); leave empty to not constrain by region", step: "Applicability", check: requires("Business Unit"), rule: { multi: true, filteredBy: "registryUnitID" } },
        "Business Units": { attribute: "businessUnitID", tooltip: "OPTIONAL unit applicability (sv107) — offers exactly the Registry unit: tick it to constrain the inheritance to that unit, leave empty to not constrain by unit", step: "Applicability", check: requires("Business Unit"), rule: { multi: true, filteredBy: "registryUnitID" } },
        "Branch": { attribute: "branchID", tooltip: "Branches this requirement applies to — leave empty to not constrain by branch; a declared branch binds the tickets whose OUTPUT Branch (chosen below the Applicant) matches it (sv108)", step: "Applicability", check: requires("Business Unit"), rule: { multi: true, filteredBy: "registryUnitID" } },
        "Customer": { attribute: "customerID", tooltip: "Customers this requirement applies to — e.g. a customer-specific design-approval template; leave empty to not constrain by customer (multivalued since #366)", step: "Applicability", check: requires("Business Unit"), rule: { multi: true, filteredBy: "registryUnitID" } },
        "Scope": { attribute: "scopeID", tooltip: "Scopes this requirement applies to", step: "Applicability", rule: { multi: true, filteredBy: "registryUnitID" } },
        "Product Group": { attribute: "productGroupID", tooltip: "Product groups this requirement applies to", step: "Applicability", rule: { multi: true, filteredBy: "registryUnitID" } },
        "Product Scope": { attribute: "productScopeID", tooltip: "Product scopes this requirement applies to directly (shown by registry code) — leave empty to not constrain; a declared subset narrows inheritance to the named combinations", step: "Applicability", rule: { multi: true, filteredBy: "registryUnitID" } },
        "Regulatory Reference": { attribute: "regulatoryReference", step: "Compliance" },
        "Reference Link": { attribute: "regulatoryURL", step: "Compliance" },
        "Activate": { attribute: "isActive", tooltip: "Make this requirement available to be applied accross the operation", step: "Compliance" },
      },
      subitemTables: null,
    }),
    cards: [],
    tableFilters: true,
    subitemTables: null,
  }),
  table(requirementType, {
    visibility: "show",
    dashboardOrder: 0,
    reports: null,
    form: formFor(requirementType.entity, {
      fields: {
        "Name": { attribute: "requirementTypeName" },
        "Description": { attribute: "requirementTypeDescription", widget: {"key":"field","hint":"shadcn-textarea"} },
      },
    }),
    cards: null,
    tableFilters: false,
  }),
]);
