/**
 * Organization module — authored in the spec (ADR-0002).
 *
 * Generated by `spec:scaffold-module Organization` from the hand-written
 * datamodel.json, then hand-maintained. Edit here and run `npm run build`;
 * never edit this module in the JSON (the CI drift guard rejects it).
 */
import { attr, computed, concat, defineModule, entity, enumOf, fk, mirror, rollup, table, userInput } from "../authoring.js";
import { requires, requiresValue } from "../behavior/check.js";
import { formFor } from "../view/form.js";

const businessUnits = entity("Business Units", "Adressess ISO 9001:2015 section 4", [
  attr("businessUnitID", "INT", { notes: "Auto-generated primary key", constraints: ["PK"], show: [false, false] }),
  attr("businessUnitName", "VARCHAR"),
  attr("businessSegmentID", "FK", { rel: fk("Business Segments", { display: "businessSegmentCode" }), notes: "multivalued", constraints: ["NOT NULL"] }),
  attr("regionID", "FK", { rel: fk("Regions", { display: "regionName" }), notes: "multivalued" }),
  attr("businessSegmentName", "mirror", { rel: mirror("Business Segments", "businessSegmentID"), notes: "multivalued", show: [false, false] }),
  attr("businessUnitTitle", "computed", { rel: concat("businessUnitName", {"lit":"-"}, "businessSegmentName"), notes: "multivalued" }),
  attr("businessUnitCode", "VARCHAR", { notes: "Short code, e.g. \"IMG\"", show: [true, true] }),
  attr("qualityManager", "FK", { rel: fk("People", { display: "userName" }) }),
  attr("operationalManager", "FK", { rel: fk("People", { display: "userName" }) }),
]);

const businessSegments = entity("Business Segments", "Adressess ISO 9001:2015 section 4", [
  attr("businessSegmentID", "INT", { notes: "Auto-generated primary key", constraints: ["PK"], show: [false, false] }),
  attr("businessSegmentName", "VARCHAR"),
  attr("businessSegmentDescription", "VARCHAR"),
  attr("businessSegmentCode", "VARCHAR", { notes: "Short code, e.g. \"ISP\"", show: [true, true] }),
  attr("businessSegmentOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3) — v3-review D7", constraints: ["FK"] }),
]);

const departments = entity("Departments", "Adressess ISO 9001:2015 section 4", [
  attr("departmentID", "INT", { notes: "Auto-generated primary key", constraints: ["PK"], show: [false, false] }),
  attr("departmentName", "VARCHAR", { show: [true, true] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), constraints: ["NOT NULL"], show: [false, false] }),
  attr("departmentCode", "VARCHAR"),
  attr("departmentManager", "FK", { rel: fk("People", { display: "userName" }) }),
  attr("businessUnitName", "mirror", { rel: mirror("Business Units", "businessUnitID", { display: "businessUnitName" }) }),
]);

const squads = entity("Squads", "Squads group People so that a manager can simulate forecastScopes by squad.", [
  attr("squadID", "INT", { notes: "Auto-generated", constraints: ["PK"], show: [false, false] }),
  attr("squadName", "VARCHAR", { show: [true, true] }),
  attr("squadType", "ENUM", { rel: enumOf("outsource", "internal"), show: [true, true] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "Form filter — narrows the Department options (pre-RBAC filter input, issue #346). Seeds: the department's unit (tools/migrate_prerbac_batch.py).", constraints: ["FK"], show: [false, false] }),
  attr("departmentID", "FK", { rel: fk("Departments", { display: "departmentName" }), constraints: ["FK","NOT NULL"], show: [true, true] }),
  attr("people", "rollup", { rel: rollup("People", "squadID"), notes: "People belonging to this squad", show: [false, false] }),
  attr("squadOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c))", constraints: ["FK"] }),
]);

const regions = entity("Regions", "Geographical grouping of customers (ISO 9001:2015 §4.1 organisational context). A region can carry execution requirements of its own: Requirements declare the regions they apply to (issue #366 — 'all regions' is every region explicitly selected).", [
  attr("regionID", "INT", { notes: "Auto-generated primary key", constraints: ["PK"], show: [false, false] }),
  attr("regionName", "VARCHAR", { notes: "e.g., EMEA, Americas, APAC", show: [true, true] }),
  attr("regionDescription", "TEXT", { notes: "nullable" }),
  attr("countryName", "FK", { rel: fk("Countries", { display: "countryName" }), notes: "multivalued — countries this region covers (drives the Branches Country picker)" }),
  attr("continent", "mirror", { rel: mirror("Countries", "countryName", { display: "continent" }), notes: "Derived — distinct continents of the selected countries (the Continent input was removed 2026-08-03; a region spanning several continents lists them all)" }),
  attr("regionOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c)) — requirements-model.md asks rollup.userID; kept as the standard owner FK", constraints: ["FK"] }),
  attr("customers", "rollup", { rel: rollup("Customers", "regionID"), notes: "Customers located in this region", show: [false, false] }),
]);

const issues = entity("Issues", "Positive and negative factors or conditions for consideration (ISO 9001:2015 §4.1/§4.2). Positive issues are Opportunities — registered top-down by managers in strategic positions (SWOT or equivalent market analysis) to drive business strategy (segmentation, units, departments). Negative issues are Risks — elevated automatically from the nonconformity flow once an investigation routes a cause to the risk class (see issue #124).", [
  attr("issueID", "INT", { constraints: ["PK"], show: [false, false] }),
  attr("issueName", "VARCHAR", { notes: "e.g., Lifetime Extension, Increase Capability, Dieletric Failure", show: [true, true] }),
  attr("issueDescription", "TEXT"),
  attr("issueType", "ENUM", { rel: enumOf("Opportunity", "Risk"), show: [true, true] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "Unit this issue classifies under (2026-08-03 reversal of the 2026-08-01 segment round — segment shows as the select group header)", constraints: ["FK"] }),
  attr("scopeID", "rollup", { rel: rollup("Scopes", "scopeOpportunity"), notes: "Scopes tagged with this issue (reverse of Scopes.scopeOpportunity)", show: [false, false] }),
  attr("businessUnitTitle", "mirror", { rel: mirror("Business Units", "businessUnitID"), notes: "unitName-segmentName; hidden by default (the Unit column covers it)", constraints: ["FK"], show: [false, false] }),
  attr("issueOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3) — v3-review D7", constraints: ["FK"] }),
]);

const branches = entity("Branches", "Physical branches (sites/units) of the organisation — segment, unit, region and country aware (stakeholder round 2026-08-01)", [
  attr("branchID", "INT", { constraints: ["PK"], show: [false, false] }),
  attr("branchName", "VARCHAR", { show: [true, true] }),
  attr("businessSegmentID", "FK", { rel: fk("Business Segments", { display: "businessSegmentName" }), notes: "multivalued — a branch can host multiple segments (issue #168)", constraints: ["NOT NULL"] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "multivalued — a branch can host multiple units (issue #168)", constraints: ["NOT NULL"] }),
  attr("departmentID", "FK", { rel: fk("Departments", { display: "departmentName" }), notes: "multivalued — user-selected departments present at the branch; options limited to the selected Units' departments (issue #169, replaces inheritance from the business unit)", constraints: ["FK"] }),
  attr("customerID", "FK", { rel: fk("Customers", { display: "customerName", filter: {"field":"customerType","value":"Internal"} }), notes: "multivalued — customers registered at this branch (2026-09-04 N:N round, schema v74, reverses the D1 single owner: a branch may serve several customers). Written from the CUSTOMER form (2026-08-03): registering a customer selects its branches and the save updates ONLY the saving customer's own membership here (applyCustomerBranches) — another customer's link is never overwritten, so no steal by construction. The Branches form has no Customer input. Nullable/empty: a branch may have no customer yet.", constraints: ["FK"] }),
  attr("cityName", "VARCHAR"),
  attr("regionID", "FK", { rel: fk("Regions", { display: "regionName" }), constraints: ["NOT NULL"] }),
  attr("countryName", "FK", { rel: fk("Countries", { display: "countryName" }), notes: "Country picker sourced from the hidden Countries registry" }),
  attr("userID", "FK", { rel: fk("People", { display: "userName" }), notes: "Branch owner — any person, options grouped by function", constraints: ["FK"] }),
]);

const countries = entity("Countries", "System registry of countries per continent — predefined in data/countries.json, never user-registered; feeds the Branches Country picker", [
  attr("countryName", "VARCHAR", { notes: "PK — name-valued", constraints: ["PK"] }),
  attr("continent", "ENUM", { rel: enumOf("Africa", "Antarctica", "Asia", "Europe", "North America", "Oceania", "South America") }),
], { systemRegistry: true });

export const organization = defineModule("Organization", 1, [
  table(businessUnits, {
    visibility: "show",
    dashboardOrder: 3,
    reports: null,
    form: formFor(businessUnits.entity, {
      fields: {
        "Segment": { attribute: "businessSegmentID" },
        "Region": { attribute: "regionID", rule: { multi: true } },
        "Name": { attribute: "businessUnitName", widget: "field" },
        "Acronym": { attribute: "businessUnitCode", widget: "field" },
        "Quality Manager": { attribute: "qualityManager", widget: "selectgroups", rule: { groupBy: "functionName" } },
        "Operational Manager": { attribute: "operationalManager", widget: "selectgroups", rule: { groupBy: "functionName" } },
      },
    }),
    cards: null,
    tableFilters: true,
    subitemTables: [
      "Branches"
    ],
  }),
  table(businessSegments, {
    visibility: "show",
    dashboardOrder: 1,
    reports: null,
    form: formFor(businessSegments.entity, {
      fields: {
        "Name": { attribute: "businessSegmentName", widget: "field" },
        "Description": { attribute: "businessSegmentDescription", widget: "field" },
        "Acronym": { attribute: "businessSegmentCode", widget: "field" },
        "Owner": { attribute: "businessSegmentOwner", check: requires("Name"), rule: { groupBy: "functionName" } },
      },
    }),
    cards: null,
    tableFilters: true,
  }),
  table(departments, {
    visibility: "show",
    dashboardOrder: 4,
    reports: null,
    form: formFor(departments.entity, {
      fields: {
        "Business Unit": { attribute: "businessUnitID", widget: "selectgroups", rule: { groupBy: "businessSegmentName" } },
        "Name": { attribute: "departmentName", widget: "field" },
        "Acronym": { attribute: "departmentCode", widget: "field" },
        "Manager": { attribute: "departmentManager", widget: "selectgroups", rule: { groupBy: "functionName" } },
      },
    }),
    cards: null,
    tableFilters: true,
    subitemTables: [
      "Squads",
      "Events"
    ],
  }),
  table(squads, {
    visibility: "show",
    dashboardOrder: 5,
    reports: null,
    form: formFor(squads.entity, {
      fields: {
        "Business Unit": { attribute: "businessUnitID", tooltip: "Pick the unit first — the Department options narrow to it (pre-RBAC filter input, issue #346)" },
        "Department": { attribute: "departmentID", widget: "selectgroups", check: requires("Business Unit"), rule: { filteredBy: "Business Unit" } },
        "Name": { attribute: "squadName", widget: "field" },
        "Type": { attribute: "squadType", rule: { enum: ["outsource","internal"] } },
        "Owner": { attribute: "squadOwner", rule: { filteredBy: "Department" } },
      },
    }),
    cards: null,
    tableFilters: true,
    subitemTables: [
      {
        "tab-order": 1,
        "rule": null,
        "tab-name": "people",
        "tab-table": "People"
      },
      {
        "tab-order": 2,
        "rule": null,
        "tab-name": "processes",
        "tab-table": "Processes"
      }
    ],
  }),
  table(regions, {
    visibility: "show",
    dashboardOrder: 2,
    reports: null,
    form: formFor(regions.entity, {
      fields: {
        "Name": { attribute: "regionName" },
        "Description": { attribute: "regionDescription", widget: {"key":"field","hint":"shadcn-textarea"} },
        "Country": { attribute: "countryName", tooltip: "Countries this region covers — offered as the Country options for the region's branches", rule: { groupBy: "continent", multi: true } },
        "Owner": { attribute: "regionOwner", check: requires("Name") },
      },
    }),
    cards: null,
    tableFilters: true,
    subitemTables: [
      "Business Units"
    ],
  }),
  table(issues, {
    visibility: "show",
    dashboardOrder: 0,
    reports: null,
    form: formFor(issues.entity, {
      fields: {
        "Name": { attribute: "issueName" },
        "Description": { attribute: "issueDescription" },
        "Type": { attribute: "issueType" },
        "Unit": { attribute: "businessUnitID", widget: "selectgroups", rule: { groupBy: "businessSegmentName" } },
        "Owner": { attribute: "issueOwner", check: requires("Name"), rule: { groupBy: "functionName" } },
      },
    }),
    cards: [],
    tableFilters: true,
    subitemTables: [
      "Scopes"
    ],
  }),
  table(branches, {
    dashboardOrder: 7,
    form: formFor(branches.entity, {
      fields: {
        "Segment": { attribute: "businessSegmentID", rule: { multi: true } },
        "Unit": { attribute: "businessUnitID", check: requires("Segment"), rule: { filteredBy: "Segment" } },
        "Departments": { attribute: "departmentID", tooltip: "Only departments of the selected Units are offered", check: requires("Unit"), rule: { filteredBy: "Unit" } },
        "Name": { attribute: "branchName" },
        "City": { attribute: "cityName" },
        "Region": { attribute: "regionID" },
        "Country": { attribute: "countryName", tooltip: "Only countries registered on the selected Region are offered", check: requires("Region"), rule: { groupBy: "continent", filteredBy: "Region.countryName" } },
        "Owner": { attribute: "userID", rule: { groupBy: "functionName" } },
      },
    }),
    subitemTables: [
      "Departments (via: departmentID)"
    ],
  }),
  table(countries, {
    dashboardOrder: 0,
    form: null,
    subitemTables: null,
  }),
]);
