/**
 * Portfolio module — authored in the spec (ADR-0002).
 *
 * Generated by `spec:scaffold-module Portfolio` from the hand-written
 * datamodel.json, then hand-maintained. Edit here and run `npm run build`;
 * never edit this module in the JSON (the CI drift guard rejects it).
 */
import { attr, computed, concat, defineModule, entity, enumOf, fk, mirror, rollup, table, userInput } from "../authoring.js";
import { requires, requiresValue } from "../behavior/check.js";
import { formFor } from "../view/form.js";

const productScopes = entity("Product Scopes", "Combination of product and scope used for planning and forecasting execution demand (ISO §4.3 / §8.1).", [
  attr("productScopeID", "INT", { notes: "Displayed as a group code, e.g. \"AA\"", constraints: ["PK"], show: [false, false] }),
  attr("productScopeRegistry", "VARCHAR", { notes: "nullable", show: [false, true] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "User input", constraints: ["FK","NOT NULL"] }),
  attr("productGroupID", "FK", { rel: fk("Product Groups", { concat: [{"field":"productName"},{"lit":" | "},{"field":"specsSummary"}] }), notes: "Options show productName | SPECS and are filtered by the selected Business Unit (via the group's products)", constraints: ["FK","NOT NULL"], show: [false, false] }),
  attr("productGroupName", "mirror", { rel: rollup("Product Groups", "productGroupID"), notes: "e.g., \"AA\"", constraints: ["rollup"], show: [true, true] }),
  attr("productName", "rollup", { rel: rollup("Products", "productGroupID"), notes: "multivalued", show: [false, false] }),
  attr("productSpecName", "rollup", { rel: rollup("Product Groups", "productGroupID", { display: "specsSummary" }), notes: "multivalued — SPECS summary of the linked Product Group (specValues map)", show: [true, true] }),
  attr("scopeID", "FK", { rel: fk("Scopes", { display: "scopeName" }), notes: "multivalued", constraints: ["FK","NOT NULL"] }),
  attr("productScopeName", "mirror", { rel: concat("productGroupName", {"lit":" | "}, "specsSummary", {"lit":" | "}, "scopeName"), notes: "Derived display name (2026-09-08 hint round, issue #372 follow-up): productGroupName | specs summary | scopeName — the authored 'X from FK' CONCAT spelling never resolved (computedConcat implements plain sibling-hop parts only, the #179 trap), so UI-created rows rendered the dash; the rule is live now and the sv102 migration DROPPED the stored demo copies (stored wins over CONCAT, #214 — demo and MVP resolve identically). Feeds the Product Scope picker hints (psOption) and every display naming this attr.", show: [false, false] }),
  attr("businessSegment", "VARCHAR", { rel: {"kind":"mirror","target":"Product Groups","via":null,"viaList":null,"display":"businessSegment","concat":null,"filter":null} }),
  attr("productScopeRequirements", "mirror", { rel: {"kind":"psrequirements","srcField":"productScopeID","display":"requirementName"}, notes: "Comprehensive requirement set (issue #288, legs inverted by #294, unit leg removed by #296): requirements NAMING this product scope ∪ those EXPLICITLY connected to the row's scope ∪ its product group — THREE connection legs only. A requirement sharing the row's businessUnitID or regionID does NOT attach through those dimensions (unit/region act purely as exclusion gates on the derived legs; unit-wide inheritance lives on the ticket/forecast chains). Still no wildcard: blank keys attach nowhere (#288 decision), and since issue #366 a MATERIALIZED full-dimension set reads the same way (namesFullDimension — 'names everything today' is global, not a specific pin; the globals-stay-out display survives the sv99 materialization). Derived legs skip Inactive requirements. Drives the REQUIREMENTS column, the Requirements subitem tab and the Procedures picker.", displayName: "REQUIREMENTS", show: [true, true] }),
  attr("isActive", "BOOLEAN", { notes: "BOOLEAN-select convention (issue #218): the form renders fixed Yes/No options and stores a real boolean.", show: [true, true] }),
  attr("createdAt", "DATETIME", { show: [false, false] }),
  attr("forecastScopes", "rollup", { rel: rollup("Forecast Scopes", "productScopeID"), show: [false, false] }),
  attr("productScopeOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c))", constraints: ["FK"], show: [false, false] }),
]);

const scopes = entity("Scopes", "Defines the work scope boundaries applicable to products — how far the service goes (e.g., Routine, Urgent, Second Opinion) — ISO §4.3.", [
  attr("scopeID", "INT", { constraints: ["PK"], show: [false, false] }),
  attr("scopeCodeID", "VARCHAR", { notes: "nullable", show: [false, false] }),
  attr("scopeName", "VARCHAR", { notes: "e.g., Routine, Urgent, Second Opinion", show: [true, true] }),
  attr("scopeDescription", "TEXT", { notes: "nullable — what activities the scope involves, so users understand it before applying it (issue #181)", show: [false, false] }),
  attr("scopeOpportunity", "FK", { rel: fk("Issues", { display: "issueName" }), notes: "Opportunity tags; multivalued; form input HIDDEN since issue #174 — the Issue/Opportunity concept confuses stakeholders and awaits reframing in the decision workflow; stored values and the Issues rollup stay intact", show: [true, true] }),
  attr("scopeClassID", "FK", { rel: fk("Classes", { display: "scopeClassName" }), notes: "multivalued" }),
  attr("productScopeID", "rollup", { rel: computed("list productScopeID from Product Scopes where scopeID matches"), show: [false, false] }),
  attr("scopeOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c))", constraints: ["FK"], show: [false, false] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "multivalued", constraints: ["FK","NOT NULL"] }),
]);

const products = entity("Products", "The products and services the division delivers (exams and procedures in the demo domain), tracked through quality and forecasting cycles (ISO §8.1).", [
  attr("productID", "INT", { constraints: ["PK"], show: [true, true] }),
  attr("productName", "VARCHAR", { show: [true, true] }),
  attr("productOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c))", constraints: ["FK"] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "multivalued", constraints: ["FK","NOT NULL"] }),
]);

const productSpecs = entity("Product Specs", "Dynamic attribute definitions for Product Groups: each spec becomes an input field in the Product Group form for the products it applies to (ISO §8.1).", [
  attr("productSpecID", "INT", { notes: "Auto-generated primary key", constraints: ["PK"], show: [false, false] }),
  attr("specName", "VARCHAR", { notes: "Becomes the attribute label in the Product Group form", show: [true, true] }),
  attr("specInputType", "ENUM", { rel: enumOf("Number", "Text", "Choice", "List", "Checkbox"), notes: "Controls the input rendered for this spec in the Product Group form — Number (decimal), Text (string), Choice (single pick from Allowed Values), List (multiple picks, stored semicolon-separated), Checkbox (boolean, shown Yes/No). Issue #205 relabel of INT/DECIMAL/String/List", constraints: ["NOT NULL"] }),
  attr("specDescription", "TEXT"),
  attr("productID", "FK", { rel: fk("Products", { display: "productName" }), notes: "multivalued — products this spec applies to", constraints: ["FK","NOT NULL"], show: [false, false] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "Derived on save from the selected products (no user input)", constraints: ["FK"], show: [false, false] }),
  attr("specOptions", "VARCHAR", { notes: "Semicolon/comma-separated allowed values; only used when specInputType is Choice or List" }),
  attr("productSpecOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c))", constraints: ["FK"], show: [false, false] }),
]);

const productGroups = entity("Product Groups", "Higher-level commercial grouping of product classes for planning (ISO §8.1).", [
  attr("productGroupID", "INT", { constraints: ["PK"], show: [false, false] }),
  attr("classCodeName", "VARCHAR"),
  attr("productGroupName", "mirror", { rel: computed("Products", { via: "productID", display: "productName" }), notes: "Derived — the selected products’ names, joined (issue #176: the legacy \"CONCAT(productName from productID)\" spelling was unparseable and the stored mockup copy went stale with 2+ products, so the name is now always derived)", show: [false, false] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "Unit this product group belongs to (2026-08-03 — replaces the former hard-coded segment enum)", show: [true, true] }),
  attr("businessSegmentName", "mirror", { rel: mirror("Business Units", "businessUnitID", { display: "businessSegmentName" }), notes: "Derived — segment(s) of the chosen unit; available via Customize Columns", show: [false, false] }),
  attr("productID", "FK", { rel: fk("Product", { display: "productName" }), notes: "multivalued — a product group can apply to several products; the group’s specs then serve all of them (issue #176). Spec fields offered in the form are the UNION of the selected products’ specs", constraints: ["NOT NULL"], show: [true, true] }),
  attr("specValues", "JSON", { notes: "Object map productSpecID → value, filled by the dynamic spec fields in the form. Never displayed raw.", show: [false, false] }),
  attr("specsSummary", "computed", { rel: {"kind":"map","srcField":"specValues","target":"Product Specs","display":"specName"}, notes: "Renders the specValues map as 'name: value' pairs — hidden by default since issue #161 (the specs expand as a subitem table); still drives the FK CONCAT displays elsewhere", displayName: "SPECS", show: [false, true] }),
  attr("productGroupOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c))", constraints: ["FK"], show: [false, false] }),
]);

const classes = entity("Classes", "Scope classification registry (stakeholder round 2026-08-01) — each class ties scopes to the Issue it addresses", [
  attr("scopeClassID", "INT", { constraints: ["PK"], show: [false, false] }),
  attr("scopeClassName", "VARCHAR", { show: [true, true] }),
  attr("scopeClassDefinition", "TEXT"),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "multivalued — units this class applies to (issue #204). Seeded as the union of the units of the scopes carrying the class (migrate_class_units.py; the seed builder backfills the same rule). Drives the Scopes form Classification narrowing: a selected Business Unit offers only its classes.", constraints: ["FK"] }),
]);

const events = entity("Events", "An Event is an aggregator of processes; it is not executed itself but triggers a defined execution. Forecasts group which events and execution parameters (forecastScopes) they contain. Corrective-action and nonconformity linkage is deferred to a future module.", [
  attr("eventID", "INT", { notes: "Auto-generated primary key", constraints: ["PK"], show: [false, false] }),
  attr("eventTitle", "VARCHAR", { notes: "Dynamic — set at creation", show: [true, true] }),
  attr("eventDescription", "TEXT", { show: [true, true] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), constraints: ["NOT NULL"], show: [true, true] }),
  attr("departmentID", "FK", { rel: fk("Departments", { display: "departmentName" }), notes: "single — the department that ANSWERS this event (issue #352, re-scoped: an event is fundamentally the request a department must fulfill for its clients; Event × Product Scope = the Payload). Form select between Business Unit and Scopes, unit-gated (generic stored-key cascade); on the Payload form the chosen Department filters the Event options. Nullable (legacy developer copy carries honest nulls); seeded by migrate_event_department_link.py — the first IN-UNIT department among the processes chaining the event (row order; the 2 cross-unit signals, EV06/EV11, fall through — the #344 divergence family, re-keying the unit stays discarded), else the unit's first department (clinic 20/20). Payloads mirror it (payload.departmentID ≡ event.departmentID — the invariant that keeps the department-filtered Event picker offering every stored pick); Departments expose the reverse Events subitem tab through this key.", constraints: ["FK"], show: [true, true] }),
  attr("scopeID", "FK", { rel: fk("Scopes", { display: "scopeName" }), notes: "Multivalued — scopes this event applies to (Payload distribution, issue #159). The empty-key wildcard is RETIRED (issue #367, the #364 doctrine): an undeclared dimension admits NOTHING — 'all scopes' is every scope explicitly selected (sv100 materialized the demo blanks; a scope registered later requires revisiting the event).", constraints: ["FK"], show: [false, false] }),
  attr("productID", "FK", { rel: fk("Products", { display: "productName" }), notes: "Multivalued — products this event applies to (issue #159). The empty-key wildcard is RETIRED (issue #367): undeclared = admits nothing; 'all products' is every product explicitly selected (sv100 materialized the demo blanks).", constraints: ["FK"], show: [false, false] }),
  attr("productGroupID", "mirror", { rel: rollup("Product Groups", "productID", { display: "productGroupName" }), notes: "Derived — product groups of the event's products (shared-field join on productID); no form input, available via Customize Columns", show: [false, false] }),
  attr("eventCreatedAt", "DATETIME", { show: [true, true] }),
  attr("processID", "rollup", { rel: rollup("Processes", "eventID", { display: "processName" }), notes: "multivalued", show: [false, false] }),
  attr("tasks", "rollup", { rel: rollup("Tasks", "eventID"), notes: "Tasks existing for each process triggered by this event", show: [false, false] }),
  attr("executionTime", "rollup", { rel: {"kind":"sum","childAttr":"tasks","field":"executionTime","multiplierField":null}, notes: "Sum over the event's tasks — each task in turn sums its procedures (nested derived sum)", show: [false, false] }),
  attr("forecastScopes", "rollup", { rel: rollup("Forecast Scopes", "eventID"), notes: "Forecast Scopes that use this event to estimate workload", show: [false, false] }),
  attr("ticketID", "rollup", { rel: rollup("Tickets", "eventID"), notes: "Open tickets for each event", show: [false, false] }),
  attr("customerName", "VARCHAR", { rel: {"kind":"mirror","target":"Tickets","via":null,"viaList":null,"display":"customerName","concat":null,"filter":null}, notes: "From ticketID rollup", show: [true, true] }),
  attr("productName", "VARCHAR", { rel: {"kind":"mirror","target":"Tickets","via":null,"viaList":null,"display":"products","concat":null,"filter":null}, notes: "From ticketID rollup", show: [true, true] }),
  attr("scopeName", "VARCHAR", { rel: {"kind":"mirror","target":"Tickets","via":null,"viaList":null,"display":"scopes","concat":null,"filter":null}, notes: "From ticketID rollup", show: [true, true] }),
  attr("eventOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c))", constraints: ["FK"], show: [false, false] }),
]);

const payload = entity("Payload", "A Payload packages one Event × Product Scopes combination — the dispatch unit that will carry the customer/SLA requirement chain into Tickets (ER-model Payload materialized, issue #190).", [
  attr("payloadID", "INT", { notes: "Auto-generated primary key", constraints: ["PK"], show: [false, false] }),
  attr("payloadCode", "VARCHAR", { notes: "Registry code, e.g. \"PLC-0001\"", constraints: ["NOT NULL"], show: [true, true] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "single valued — the unit whose events this payload dispatches", constraints: ["FK","NOT NULL"], show: [false, false] }),
  attr("departmentID", "FK", { rel: fk("Departments", { display: "departmentName" }), notes: "single valued — the department that supplies this payload (2026-09-03 round; spec wrote a rollup via the unit — normalized to a stored FK: the form select and the SLA Payloads department filter need the stored key). Since issue #352 it carries the INVARIANT payload.departmentID ≡ event.departmentID (the event owns the answering department; the payload mirrors it so the department-filtered Event picker keeps offering every stored pick — migrate_event_department_link.py re-keyed 3 clinic payloads and keyed the 4 formerly-null admin ones). On the form the Department is picked FIRST and the Event options follow it (pre-RBAC filter-input doctrine #334)", constraints: ["FK"], show: [true, true] }),
  attr("eventID", "FK", { rel: fk("Events", { display: "eventTitle" }), notes: "user-selected, filtered by the business unit (spec wrote a rollup — normalized to a stored FK, the select must store the PK)", constraints: ["FK","NOT NULL"], show: [true, true] }),
  attr("productScopeID", "FK", { rel: fk("Product Scopes", { display: "productScopeRegistry" }), notes: "multivalued — user-selected from the event's applicability (scopeID × productID, issue #190). The empty-packaging wildcard is RETIRED (issue #367): an unpackaged payload packages NOTHING — 'everything the event admits' is every scope explicitly selected (sv100 materialized the demo blanks with the event's applicability; pre-sv100 snapshots keep the Q1 widening via legacyWildcardData)", constraints: ["FK"], show: [true, true] }),
  attr("isActive", "ENUM", { rel: enumOf("Active", "Inactive"), show: [true, true] }),
  attr("payloadOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Broker role (ISO §5.3) — accountable for wiring the event to its product scopes; seeded from the event's owner, no form input", constraints: ["FK"], show: [false, false] }),
]);

export const portfolio = defineModule("Portfolio", 2, [
  table(productScopes, {
    visibility: "show",
    dashboardOrder: 7,
    reports: null,
    form: formFor(productScopes.entity, {
      fields: {
        "Registry ID": { attribute: "productScopeRegistry", tooltip: "businee unit unique ID" },
        "Business Unit": { attribute: "businessUnitID", widget: "selectgroups", rule: { groupBy: "businessSegmentName" } },
        "Product Group": { attribute: "productGroupID", widget: "combobox", check: requires("Business Unit"), rule: { filteredBy: "businessUnitID" } },
        "Scope": { attribute: "scopeID", widget: "comboboxgroups", check: requires("Business Unit"), rule: { filteredBy: "businessUnitID" } },
        "Active": { attribute: "isActive", tooltip: "Soft-delete flag — inactive product scopes stay registered but are retired from operation", rule: { default: "Yes" } },
      },
    }),
    cards: [],
    tableFilters: true,
    subitemTables: [
      {
        "tab-order": 1,
        "rule": "(via: productScopeRequirements)",
        "tab-name": "Requirements",
        "tab-table": "Requirements"
      }
    ],
  }),
  table(scopes, {
    visibility: "show",
    dashboardOrder: 2,
    reports: null,
    form: formFor(scopes.entity, {
      fields: {
        "Code": { attribute: "scopeCodeID" },
        "Name": { attribute: "scopeName" },
        "Description": { attribute: "scopeDescription", widget: "field", tooltip: "What activities does this scope involve?" },
        "Business Unit": { attribute: "businessUnitID" },
        "Classification": { attribute: "scopeClassID", tooltip: "Classes offered follow the selected Business Unit (issue #204); no unit selected = every class", rule: { multi: true, filteredBy: "Business Unit" } },
      },
    }),
    cards: [],
    tableFilters: true,
    subitemTables: [
      "Product Scopes"
    ],
  }),
  table(products, {
    visibility: "show",
    dashboardOrder: 3,
    reports: null,
    form: formFor(products.entity, {
      fields: {
        "Product Name": { attribute: "productName" },
        "Business Unit": { attribute: "businessUnitID" },
        "Owner": { attribute: "productOwner", widget: "selectgroups", rule: { groupBy: "functionName", filteredBy: "businessUnitID" } },
      },
    }),
    cards: null,
    tableFilters: true,
  }),
  table(productSpecs, {
    visibility: "show",
    dashboardOrder: 4,
    reports: null,
    form: formFor(productSpecs.entity, {
      fields: {
        "Spec Name": { attribute: "specName" },
        "Input Type": { attribute: "specInputType" },
        "Description": { attribute: "specDescription", widget: {"key":"field","hint":"shadcn-textarea"} },
        "Products": { attribute: "productID", tooltip: "Products this spec applies to", rule: { multi: true } },
        "Allowed Values": { attribute: "specOptions", tooltip: "Semicolon-separated; only used when Input Type is Choice or List", check: requiresValue("Input Type", "Choice", "List") },
      },
    }),
    cards: null,
    tableFilters: true,
    subitemTables: [
      "Products"
    ],
  }),
  table(productGroups, {
    visibility: "show",
    dashboardOrder: 5,
    reports: null,
    form: formFor(productGroups.entity, {
      fields: {
        "Class Code": { attribute: "classCodeName" },
        "Business Unit": { attribute: "businessUnitID" },
        "Product": { attribute: "productID", check: requires("Business Unit"), rule: { filteredBy: "businessUnitID" } },
        "Specs": { attribute: "specValues", tooltip: "Spec attributes of the selected Product", check: requires("Product"), rule: { specsOf: "Product" } },
      },
    }),
    cards: [],
    tableFilters: true,
    subitemTables: [
      "Product Specs (map: specValues)"
    ],
  }),
  table(classes, {
    dashboardOrder: 1,
    form: formFor(classes.entity, {
      fields: {
        "Name": { attribute: "scopeClassName" },
        "Definition": { attribute: "scopeClassDefinition", widget: "field" },
        "Business Units": { attribute: "businessUnitID", tooltip: "Units this class applies to — a class left without units stays out of unit-filtered pickers", rule: { multi: true } },
      },
    }),
    subitemTables: [
      "Scopes"
    ],
  }),
  table(events, {
    visibility: "show",
    dashboardOrder: 6,
    reports: {
      "Report-A": {
        "graph_type": "bar",
        "rule": "Total executionTime per Event",
        "filters": null
      },
      "Report-B": {
        "graph_type": "bar",
        "rule": "Tasks count by Events",
        "filters": null
      }
    },
    form: formFor(events.entity, {
      fields: {
        "Event": { attribute: "eventTitle" },
        "Description": { attribute: "eventDescription" },
        "Business Unit": { attribute: "businessUnitID" },
        "Department": { attribute: "departmentID", tooltip: "The department that answers this event (issue #352) — the request it must fulfill for its clients; offered from the selected Business Unit's departments", check: requires("Business Unit"), rule: { filteredBy: "Business Unit" } },
        "Scopes": { attribute: "scopeID", tooltip: "Scopes this event applies to — select every scope to apply to all of today's list (issue #367; an empty list admits nothing)", check: requires("Business Unit"), rule: { list: true, multi: true, filteredBy: "businessUnitID" } },
        "Products": { attribute: "productID", tooltip: "Products this event applies to — select every product to apply to all of today's list (issue #367; an empty list admits nothing)", check: requires("Scope"), rule: { list: true, multi: true, filteredBy: "businessUnitID" } },
      },
    }),
    cards: null,
    tableFilters: true,
    subitemTables: [
      {
        "tab-order": 1,
        "rule": null,
        "tab-name": "processes",
        "tab-table": "Processes"
      },
      {
        "tab-order": 2,
        "rule": "(via: scopeID)",
        "tab-name": "product scopes",
        "tab-table": "Product Scopes"
      }
    ],
  }),
  table(payload, {
    visibility: "show",
    dashboardOrder: 8,
    reports: null,
    form: formFor(payload.entity, {
      fields: {
        "Code": { attribute: "payloadCode" },
        "Business Unit": { attribute: "businessUnitID", widget: "selectgroups", tooltip: "Unit whose events this payload dispatches", rule: { groupBy: "businessSegmentName" } },
        "Department": { attribute: "departmentID", rule: { filteredBy: "businessUnitID" } },
        "Event": { attribute: "eventID", tooltip: "The event this payload packages — only the selected Business Unit's events and, once a Department is chosen, only the requests that department answers (issue #352)", check: requires("Business Unit"), rule: { filteredBy: "Business Unit + Department" } },
        "Product Scope": { attribute: "productScopeID", tooltip: "Product scopes this payload packages — select every offered scope to package all of the event's applicability (issue #367; an empty list packages nothing)", check: requires("Event"), rule: { list: true, multi: true, filteredBy: "Event + Business Unit" } },
        "Activate": { attribute: "isActive", tooltip: "Make this payload available across the operation" },
      },
    }),
    cards: null,
    tableFilters: true,
    subitemTables: null,
  }),
], {
  suppress: {
    "Scopes.productScopeID": "#412: computed target \"list productScopeID from Product Scopes where scopeID matches\" is not an entity (malformed rule?)",
    "Product Groups.productID": "#412: fk target \"Product\" is not an entity"
  },
});
