/**
 * Talent module — authored in the spec (ADR-0002).
 *
 * Generated by `spec:scaffold-module Talent` from the hand-written
 * datamodel.json, then hand-maintained. Edit here and run `npm run build`;
 * never edit this module in the JSON (the CI drift guard rejects it).
 */
import { attr, computed, concat, defineModule, entity, enumOf, fk, mirror, rollup, table, userInput } from "../authoring.js";
import { requires, requiresValue } from "../behavior/check.js";
import { formFor } from "../view/form.js";

const roles = entity("Roles", "Organisational role belonging to a Function and exercised in Departments (ISO §5.3). The skill level is defined per Competence and the job family inherits through the Function (issue #328). Resolves all *Owner foreign keys in the model.", [
  attr("roleID", "INT", { constraints: ["PK"], show: [false, false] }),
  attr("roleName", "VARCHAR", { notes: "e.g., \"Planner\", \"Design Engineer\"", show: [true, true] }),
  attr("roleDescription", "TEXT", { notes: "Free-text description of the role (issue #336). Demo seeds: deterministic generated text — tools/migrate_role_description.py, same rule in the seed builder." }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "Single-valued — the unit whose functions this role registration works with (issue #334). PRE-RBAC FILTER-INPUT doctrine: until RBAC lands, forms carry inputs whose purpose is purely to NARROW the remaining options so the MVP serves different Business Segments/Units — the filter is a stored FK (the generic stored-key cascade reads sibling stored keys; there is no unstored form-field concept), seeded so existing rows survive the gated picker (form-integrity). Seeds: the role's function's (first) unit — tools/migrate_role_unit_filter.py.", constraints: ["FK","NOT NULL"] }),
  attr("functionID", "FK", { rel: fk("Functions", { display: "functionName" }), notes: "Functional area this role belongs to; the form combobox is gated on Business Unit and offers only the selected unit's functions (issue #334 — generic stored-key cascade on Functions.businessUnitID)", constraints: ["FK","NOT NULL"], show: [true, true] }),
  attr("departmentID", "FK", { rel: fk("Departments", { display: "departmentName" }), notes: "multivalued — departments where this role is exercised (issue #328); options = the departments of the selected function's business units (generic shared-unit join Functions.businessUnitID × Departments.businessUnitID). The businessUnitName grouping was dropped in #334 — with the Business Unit now a USER decision on this form, the offered departments all belong to the chosen unit and the group header was redundant.", constraints: ["FK"], show: [true, true] }),
  attr("quantity", "INT", { rel: computed(null), notes: "Number of headcount allocated to this role", show: [true, true] }),
  attr("competenceID", "rollup", { rel: rollup("Competence", "roleID", { display: "competenceName" }), show: [false, false] }),
  attr("taskName", "rollup", { rel: rollup("Competence", "roleID", { display: "taskName" }), notes: "Task names of the role's competences — the engine resolves taskName through Competence.taskID → Tasks (#414: was an English sentence)", show: [false, false] }),
  attr("people", "rollup", { rel: rollup("People", "roleID"), notes: "People currently holding this role", show: [false, false] }),
  attr("squadID", "VARCHAR", { rel: rollup("People", "roleID", { display: "squadName" }), notes: "Squads of the people currently holding this role", show: [true, true] }),
  attr("roleOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c))", constraints: ["FK"], show: [false, false] }),
]);

const skillLevels = entity("Skill Levels", "Proficiency level descriptor applied by a Competence (ISO §7.2). Roles carry no direct skill level since issue #328 — the competence defines the role + level pair, and a person accumulates those pairs through onboarding.", [
  attr("skillLevelID", "INT", { constraints: ["PK"], show: [false, false] }),
  attr("levelName", "VARCHAR", { notes: "e.g., Junior / Senior / Expert", show: [true, true] }),
  attr("levelDescription", "TEXT", { notes: "e.g., \"0–3 years of experience\"", show: [true, true] }),
  attr("competences", "rollup", { rel: rollup("Competence", "skillLevelID", { display: "competenceTitle" }), notes: "Competences requiring this skill level — the role ↔ skill level link is indirect since issue #328 (the competence defines the role + skill level pair)", show: [false, false] }),
  attr("skillLevelOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c))", constraints: ["FK"], show: [false, false] }),
]);

const functions = entity("Functions", "Job function defining the functional scope of work a role performs (ISO §7.2).", [
  attr("functionID", "INT", { constraints: ["PK"] }),
  attr("functionName", "VARCHAR", { notes: "e.g., Electrical Design, Mechanical Design, Analyst", show: [true, true] }),
  attr("functionDescription", "TEXT"),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "multivalued", constraints: ["NOT NULL"], show: [true, true] }),
  attr("jobFamilyID", "FK", { rel: fk("Job Family", { display: "jobFamilyName" }), notes: "A function belongs to a Job Family (issue #298); nullable — legacy functions without a roles signal stay unkeyed. People derive their family through the selected function (the People form no longer picks it)", constraints: ["FK"], show: [true, true] }),
  attr("roles", "rollup", { rel: rollup("Roles", "functionID", { display: "roleName" }), notes: "multivalued", show: [false, false] }),
  attr("functionOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c))", constraints: ["FK"], show: [false, false] }),
]);

const people = entity("People", "Individual users and team members (ISO §5.3 / §7.1.2). All *Owner foreign keys across the model resolve to a Person.", [
  attr("userID", "INT", { constraints: ["PK"], show: [false, false] }),
  attr("userName", "VARCHAR", { show: [true, true] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "Business unit this person belongs to", constraints: ["FK","NOT NULL"], show: [false, false] }),
  attr("departmentID", "FK", { rel: fk("Departments", { display: "departmentName" }), notes: "Stored, user-selected (Unit → Department → Squad cascade in the form); kept consistent with squadID → Squads.departmentID", constraints: ["FK","NOT NULL"], show: [false, false] }),
  attr("userEmail", "VARCHAR"),
  attr("regionID", "FK", { rel: fk("Regions", { display: "regionName" }), constraints: ["FK","NOT NULL"] }),
  attr("countryName", "FK", { rel: fk("Countries", { display: "countryName" }), notes: "Person's location country (issues #170/#167) — picker sourced from the hidden Countries registry, limited to the selected Region's countries; seeded from the branch, editable independently (the branch is optional, the location is not)", constraints: ["NOT NULL"] }),
  attr("cityName", "VARCHAR", { notes: "nullable — city of the person's location (issue #170); seeded from the branch when present", show: [false, false] }),
  attr("isActive", "ENUM", { rel: enumOf("Active", "Inactive"), show: [true, true] }),
  attr("hireDate", "DATE", { notes: "nullable", show: [true, true] }),
  attr("functionID", "FK", { rel: fk("Functions", { display: "functionName" }), constraints: ["FK","NOT NULL"], show: [true, true] }),
  attr("squadID", "FK", { rel: fk("Squads", { display: "squadName" }), constraints: ["FK"], show: [true, true] }),
  attr("branchID", "FK", { rel: fk("Branches", { display: "branchName" }), notes: "nullable — branch (site) this person is stationed at; since #170 the geographic location lives on the person (region → country → city), the branch is organisational only", constraints: ["FK"] }),
  attr("jobFamilyID", "mirror", { rel: mirror("Functions", "functionID", { display: "jobFamilyName" }), notes: "Derived through the selected Function since issue #298 (a function belongs to a Job Family) — the People form no longer picks it; the legacy stored copies were dropped (parity)" }),
  attr("onboardID", "VARCHAR", { rel: computed("Onboarding", { via: "userID" }), show: [false, false] }),
  attr("roleID", "rollup", { rel: mirror("Roles", "functionID", { display: "roleName" }), notes: "Role(s) held by this person, resolved from the person's function (Roles.functionID). Onboards did not carry a resolvable role, which rendered skill-level codes.", constraints: ["FK"] }),
  attr("workingHours", "DECIMAL", { notes: "Weekly working-hour capacity per person (7 h/day × 5 days = 35 h/week baseline). Summed by functionID to feed Capacity availableHours per function." }),
  attr("personOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c))", constraints: ["FK"], show: [false, false] }),
]);

const onboarding = entity("Onboarding", "Tracks a person's certification progress against the competences derived from their function and roles (ISO §7.2).", [
  attr("onboardID", "INT", { notes: "Auto-generated primary key", constraints: ["PK"], show: [false, false] }),
  attr("onboardingTitle", "VARCHAR", { rel: userInput(), notes: "Context label for the certified competence GROUP (issue #239) — first *Title attr, so it is the table label (and therefore required in the form)", constraints: ["NOT NULL"], show: [true, true] }),
  attr("departmentID", "FK", { rel: fk("Departments", { display: "departmentName" }), notes: "Department running the onboarding; businessUnitID derives from it on save", constraints: ["FK","NOT NULL"] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), show: [true, true] }),
  attr("functionID", "VARCHAR", { rel: rollup("Functions", "businessUnitID", { display: "functionID" }) }),
  attr("roleID", "mirror", { rel: rollup("Roles", "functionID", { display: "roleName" }), notes: "Role resolved from the onboarding's function (Roles.functionID); display: roleName via the Roles table which owns that field." }),
  attr("userID", "INT", { rel: rollup("People", "businessUnitID", { display: "userName" }), constraints: ["FK","NOT NULL"] }),
  attr("levelRank", "ENUM", { rel: enumOf("1", "2", "3"), notes: "Ordering key (1 = lowest)", show: [true, true] }),
  attr("competenceID", "FK", { rel: fk("Competence", { display: "competenceTitle" }), notes: "multivalued — the competence GROUP this onboarding certifies (1:many since issue #239; isCertified covers the whole group). Stores competence PKs; displayed by the user-given competenceTitle since issue #284. Role/rank/department narrowing lives in the form cascade (the old 'via: roleID + levelRank' spelling made the select store roleIDs)", show: [false, true] }),
  attr("isCertified", "BOOLEAN", { notes: "Certification gate — a person only qualifies for the Tasks Users column (CERTIFIED-USERS, issue #214) and the Jobs Responsible control when this is true. BOOLEAN-select convention (issue #218): the form renders fixed Yes/No options and stores a real boolean.", show: [true, true] }),
  attr("scopeName", "VARCHAR", { rel: computed("Competence", { via: "competenceID" }), show: [true, true] }),
  attr("productName", "VARCHAR", { rel: computed("Competence", { via: "competenceID" }) }),
  attr("productSpecName", "mirror", { rel: computed("Competence", { via: "competenceID" }), show: [true, true] }),
  attr("resources", "VARCHAR", { rel: computed("Competence", { via: "roleID" }), show: [false, false] }),
  attr("requirementName", "VARCHAR", { rel: computed("Competence", { via: "competenceID" }) }),
  attr("trainingURL", "VARCHAR", { rel: userInput(), show: [true, true] }),
  attr("onboardingOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c))", constraints: ["FK"], show: [false, false] }),
]);

const competence = entity("Competence", "Competence profile mapping skills to roles, scopes and products (ISO §7.2), derived largely from the Tasks a role performs.", [
  attr("competenceID", "INT", { constraints: ["PK"], show: [false, false] }),
  attr("competenceTitle", "VARCHAR", { rel: userInput(), notes: "Label for the competence (issue #284; the Title INPUT left the form on 2026-09-08 — Rafael's call): auto-derived on save when blank via the #284 seed rule — '<task name> | <scope name>' → task name → 'Competence <id>' (applyDerivedUnits in forms.js; updateRecord merges, so stored titles survive edits). First *Title attr = the table label; NOT NULL is satisfied by the derive", constraints: ["NOT NULL"], show: [true, true] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "Form filter — narrows the Function options (pre-RBAC filter input, issue #346; the Event leg stays UNfiltered — the #344 event-unit divergence). Seeds: the function's unit (tools/migrate_prerbac_batch.py).", constraints: ["FK"], show: [false, false] }),
  attr("eventID", "FK", { rel: fk("Events", { display: "eventTitle" }), constraints: ["FK","NOT NULL"], show: [true, true] }),
  attr("departmentID", "FK", { rel: fk("Departments", { display: "departmentName" }), notes: "Derived on save from the selected Event (Event.departmentID) — join key for the Onboarding Department → Competence cascade", constraints: ["FK"], show: [false, false] }),
  attr("processID", "FK", { rel: fk("Processes", { display: "processName" }), notes: "Process context for the certified task", constraints: ["FK"], show: [false, true] }),
  attr("productScopeID", "FK", { rel: fk("Product Scopes", { concat: [{"field":"productName"},{"lit":" | "},{"field":"scopeName"}] }), notes: "The product scope this competence certifies (scope × product group in one key — replaces the separate Scope/Product Group selects, issue #159 follow-up). Options = the selected process's list.", constraints: ["FK","NOT NULL"], show: [false, false] }),
  attr("scopeID", "mirror", { rel: computed("Product Scopes", { via: "productScopeID", display: "scopeName" }), notes: "Derived — the scope of the certified product scope", show: [true, true] }),
  attr("functionID", "FK", { rel: fk("Functions", { display: "functionName" }), constraints: ["FK","NOT NULL"] }),
  attr("skillLevelID", "FK", { rel: fk("Skill Levels", { display: "levelName" }), notes: "Required proficiency", constraints: ["FK","NOT NULL"] }),
  attr("roleID", "FK", { rel: fk("Roles", { display: "roleName" }), notes: "Filtered by the selected function in the form (issue #328 — the role ↔ skill level link is indirect: this competence defines the pair)", constraints: ["FK"] }),
  attr("levelRank", "ENUM", { rel: enumOf("1", "2", "3"), notes: "Step of the professional INSIDE the competence's skill level (Rafael, 03/08): rank 1 = a newly promoted/hired professional at that level may hold the competence; holding rank 3 on every competence of a skill level signals readiness to move up a level (promotion automation: issue #149)", show: [true, true] }),
  attr("taskID", "INT", { rel: {"kind":"rollup","target":"Tasks","via":"eventID","viaList":["eventID","processID"],"display":"taskName","concat":null,"filter":null}, notes: "Task this competence certifies; options filtered by event + process", show: [false, false] }),
  attr("actionID", "FK", { rel: fk("Actions", { display: "actionName" }), notes: "Via taskID", show: [true, true] }),
  attr("activityID", "FK", { rel: fk("Activities", { display: "activityName" }), notes: "Via taskID", show: [true, true] }),
  attr("productGroupID", "mirror", { rel: computed("Product Scopes", { via: "productScopeID", display: "productGroupName" }), notes: "Derived — the product group of the certified product scope (renders the productName | SPECS display)", show: [true, true] }),
  attr("productSpecID", "FK", { rel: fk("Product Specs", { display: "specName" }), notes: "multivalued — spec definitions certified by this competence", constraints: ["FK"], show: [false, true] }),
  attr("productSpecName", "mirror", { rel: computed("Product Specs", { via: "productSpecID", display: "specName" }), show: [false, true] }),
  attr("procedureID", "FK", { rel: fk("Procedures", { display: "procedureRegistry" }), notes: "multivalued — the procedure GROUP this competence certifies (1:many since issue #284, reverting the #231 1:1; group restricted to the competence's TASK — the picker filters by Task). The quality manager's requirement decision lives on the Procedure; the competence inherits the UNION of its procedures' sets (since issue #364 an empty-set procedure contributes nothing — the #284 wildcard decision is superseded). Since issue #368 a competence with NO procedure link is INERT on sv101+ data (covers nothing, not exercisable — nothing to exercise; frozen stored-requirement rows keep the old tolerance). Deliberately nullable: the legacy developer copy predates the Procedures chain — the engine gates close the hole instead of a NOT NULL.", constraints: ["FK"], show: [true, true] }),
  attr("requirementID", "mirror", { rel: computed("Procedures", { via: "procedureID", display: "requirementName" }), notes: "Derived — requirements certified through the linked procedure GROUP: the UNION of the procedures' sets (1:many since issue #284; a procedure with an empty set applies to all, Q1 — one wildcard procedure in the group certifies everything). Doctrine (issue #231, kept in #284): a requirement NEVER enters a competence automatically — the quality manager decides on the Procedure (its Requirements picker already offers the context-aligned options), and the competence inherits the procedures' sets. Legacy stored requirementID still honoured as fallback when no procedure is linked." }),
  attr("competenceName", "mirror", { rel: concat("[taskName]", {"lit":" for "}, "[scopeName]", {"lit":" of "}, "[productGroupName]", {"lit":" applied to "}, "[{requirementTypeName: requirementName}]"), notes: "Rendered from the CONCAT rule at display time (not stored)" }),
  attr("channelName", "mirror", { notes: "Derived, not yet computable: the channel names of every input and output handout of the linked procedures — a 3-hop chain (Competence → Procedures → Handouts → Channels) the engine cannot derive in one rule. Hidden until an engine feature computes it (#414). Kept as type mirror (derived) so the validator does not expect a stored value.", show: [false, false] }),
  attr("resources", "VARCHAR", { notes: "Training resource/modality, e.g. e-learning (nullable)", show: [false, false] }),
  attr("competenceOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c))", constraints: ["FK"], show: [false, false] }),
]);

const jobFamily = entity("Job Family", "Job family a role or resource belongs to — the HR-management standard grouping (ISO §7.2). Renamed from Graduation (issue #166): education titles/institutions added no value to the model. The 'field' category label became the free-text jobFamilyDescription (issue #328).", [
  attr("jobFamilyID", "INT", { constraints: ["PK"], show: [false, false] }),
  attr("jobFamilyName", "VARCHAR", { notes: "e.g., Electrical Design, Mechanical Design (issue #166 — was graduationTitle)", show: [true, true] }),
  attr("jobFamilyDescription", "TEXT", { notes: "Free-text description of the family (issue #328 — was the 'field' category label, e.g. Engineering)" }),
  attr("jobFamilyOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c))", constraints: ["FK"], show: [false, false] }),
]);

export const talent = defineModule("Talent", 4, [
  table(roles, {
    visibility: "show",
    dashboardOrder: 2,
    reports: {
      "Report-A": {
        "graph_type": "donut",
        "rule": "Sum of quantity grouped by functionID (headcount distribution by function)",
        "filters": [
          "functionID (default: ALL)",
          "isActive (default: true)"
        ],
        "overview-display": true
      }
    },
    form: formFor(roles.entity, {
      fields: {
        "Role Name": { attribute: "roleName" },
        "Description": { attribute: "roleDescription", widget: {"key":"field","hint":"shadcn-textarea"} },
        "Business Unit": { attribute: "businessUnitID", tooltip: "Pick the unit first — the Function options narrow to it (pre-RBAC filter input, issue #334)" },
        "Function": { attribute: "functionID", widget: "combobox", tooltip: "Functions of the selected Business Unit", check: requires("Business Unit"), rule: { filteredBy: "Business Unit" } },
        "Departments": { attribute: "departmentID", widget: "selectgroups", tooltip: "Departments where this role is exercised — offered from the selected function's business units", check: requires("Function"), rule: { list: true, multi: true, filteredBy: "Function" } },
      },
      subitemTables: [
        "competence"
      ],
    }),
    cards: [],
    tableFilters: true,
    subitemTables: [
      "Competence"
    ],
  }),
  table(skillLevels, {
    visibility: "show",
    dashboardOrder: 3,
    reports: {
      "Report-A": {
        "graph_type": "pizza",
        "rule": "COUNT(Competence) grouped by levelName — the role link is indirect since issue #328: the skill level is defined per competence",
        "filters": [
          "functionID (default: ALL)"
        ]
      },
      "Report-B": null
    },
    form: formFor(skillLevels.entity, {
      fields: {
        "Level Title": { attribute: "levelName" },
        "Description": { attribute: "levelDescription", widget: {"key":"field","hint":"shadcn-textarea"} },
      },
    }),
    cards: {
      "Card 1-1": {
        "title": "most competences",
        "card-rules": {
          "main-data": "Skill level with the most registered competences",
          "trend-data": null,
          "detail-data": "levelName"
        },
        "card-component": "shadcn-card",
        "card-tooltip": "Skill level required by the largest number of competences (issue #328 — the level applies through the competence, not the role).",
        "overview-display": true
      }
    },
    tableFilters: true,
  }),
  table(functions, {
    visibility: "show",
    dashboardOrder: 4,
    reports: {
      "Report-A": {
        "graph_type": "bar",
        "rule": "SUM(Roles.quantity) grouped by functionName",
        "filters": []
      },
      "Report-B": null
    },
    form: formFor(functions.entity, {
      fields: {
        "Title": { attribute: "functionName" },
        "Description": { attribute: "functionDescription" },
        "Business Unit": { attribute: "businessUnitID" },
        "Job Family": { attribute: "jobFamilyID", tooltip: "The job family this function belongs to — people inherit it through their function" },
      },
    }),
    cards: [],
    tableFilters: true,
  }),
  table(people, {
    visibility: "show",
    dashboardOrder: 6,
    reports: {
      "Report-A": {
        "graph_type": "bar",
        "rule": "Count of active People grouped by functionID",
        "filters": [
          "departmentID",
          "countryName",
          "isActive"
        ]
      },
      "Report-B": null
    },
    form: formFor(people.entity, {
      fields: {
        "Region": { attribute: "regionID" },
        "Country": { attribute: "countryName", tooltip: "Only countries registered on the selected Region are offered", check: requires("Region"), rule: { groupBy: "continent", filteredBy: "Region.countryName" } },
        "City": { attribute: "cityName", tooltip: "Optional — city of the person's location" },
        "Unit": { attribute: "businessUnitID", widget: "selectgroups", check: requires("Region"), rule: { groupBy: "businessSegmentName", filteredBy: "regionID" } },
        "Department": { attribute: "departmentID", check: requires("Unit"), rule: { filteredBy: "businessUnitID" } },
        "Squad": { attribute: "squadID", check: requires("Department"), rule: { filteredBy: "departmentID" } },
        "Branch": { attribute: "branchID", widget: {"key":"radio","hint":"shadcn-radio button"}, tooltip: "Branch this person is stationed at — optional", check: requires("Unit"), rule: { filteredBy: "businessUnitID" } },
        "Name": { attribute: "userName" },
        "Email": { attribute: "userEmail" },
        "Active": { attribute: "isActive" },
        "Hire Date": { attribute: "hireDate" },
        "Function": { attribute: "functionID" },
      },
    }),
    cards: null,
    tableFilters: true,
    subitemTables: [
      "Onboarding"
    ],
  }),
  table(onboarding, {
    visibility: "show",
    dashboardOrder: 7,
    reports: null,
    form: formFor(onboarding.entity, {
      fields: {
        "Title": { attribute: "onboardingTitle", tooltip: "Names the competence group this onboarding certifies" },
        "Business Unit": { attribute: "businessUnitID", tooltip: "Pick the unit first — the Department options narrow to it (pre-RBAC filter input, issue #346)" },
        "Department": { attribute: "departmentID", widget: "selectgroups", check: requires("Business Unit"), rule: { filteredBy: "Business Unit" } },
        "Role": { attribute: "roleID", check: requires("Department"), rule: { note: "rollup by Talent selected" } },
        "Talent": { attribute: "userID", widget: "selectgroups", check: requires("Department"), rule: { groupBy: "functionName", filteredBy: "departmentID" } },
        "Skill Rank": { attribute: "levelRank", check: requires("Role") },
        "Competence": { attribute: "competenceID", widget: "selectgroups", tooltip: "Competences of the selected Department (via their event) matching the chosen Role", check: requires("Role"), rule: { groupBy: "processName", filteredBy: "departmentID + roleID" } },
        "Training Material": { attribute: "trainingURL" },
        "Certified": { attribute: "isCertified", tooltip: "Certifies the whole competence group of this onboarding" },
      },
    }),
    cards: null,
    tableFilters: true,
    subitemTables: [
      {
        "tab-order": 1,
        "rule": "(via: competenceID)",
        "tab-name": "Competences",
        "tab-table": "Competence"
      }
    ],
  }),
  table(competence, {
    visibility: "show",
    dashboardOrder: 8,
    reports: null,
    form: formFor(competence.entity, {
      fields: {
        "Business Unit": { attribute: "businessUnitID", tooltip: "Pick the unit first — the Function options narrow to it (pre-RBAC filter input, issue #346)" },
        "Function": { attribute: "functionID", check: requires("Business Unit"), rule: { filteredBy: "Business Unit" } },
        "Skill Level": { attribute: "skillLevelID" },
        "Role": { attribute: "roleID", check: requires("Function"), rule: { filteredBy: "Function" } },
        "Event": { attribute: "eventID" },
        "Process": { attribute: "processID", check: requires("Event"), rule: { filteredBy: "Event" } },
        "Product Scope": { attribute: "productScopeID", tooltip: "Product scope this competence certifies — offered from the selected process's list (scope and product group derive from it)", check: requires("Process"), rule: { filteredBy: "processID" } },
        "Task": { attribute: "taskID", check: requires("Process"), rule: { filteredBy: "Event + Process" } },
        "Procedure": { attribute: "procedureID", widget: "selectgroups", tooltip: "The procedures of the selected task that this competence certifies (group, 1:many — the union of their requirement sets is inherited)", check: requires("Task"), rule: { list: true, filteredBy: "Task" } },
        "Skill Rank": { attribute: "levelRank" },
      },
    }),
    cards: null,
    tableFilters: true,
  }),
  table(jobFamily, {
    visibility: "show",
    dashboardOrder: 5,
    reports: {
      "Report-A": {
        "graph_type": "donut",
        "rule": "SUM(Roles.quantity) grouped by jobFamilyName — the family resolves through the role's function (Functions.jobFamilyID, issue #328)",
        "filters": []
      },
      "Report-B": null
    },
    form: formFor(jobFamily.entity, {
      fields: {
        "Name": { attribute: "jobFamilyName" },
        "Description": { attribute: "jobFamilyDescription", widget: {"key":"field","hint":"shadcn-textarea"} },
      },
    }),
    cards: null,
    tableFilters: true,
    subitemTables: [
      "people"
    ],
  }),
]);
