/**
 * Workspace module — authored in the spec (ADR-0002).
 *
 * Generated by `spec:scaffold-module Workspace` from the hand-written
 * datamodel.json, then hand-maintained. Edit here and run `npm run build`;
 * never edit this module in the JSON (the CI drift guard rejects it).
 */
import { attr, computed, concat, defineModule, entity, enumOf, fk, mirror, rollup, table, userInput } from "../authoring.js";
import { requires, requiresValue } from "../behavior/check.js";
import { formFor } from "../view/form.js";

const tickets = entity("Tickets", "A Ticket is a project-linked work item capturing the execution context of a project's service process. It is the entry point for jobs; Customers, Planners and Managers can create tickets (ISO §10.2).", [
  attr("ticketID", "INT", { constraints: ["PK"], show: [true, true] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "single valued — anchors the Customer/Event cascade (issue #192); seeded from the ticket's customer", constraints: ["FK","NOT NULL"], show: [false, false] }),
  attr("projectID", "FK", { rel: fk("Projects", { display: "projectRegistryID" }), constraints: ["FK","NOT NULL"], show: [true, true] }),
  attr("applicantID", "FK", { rel: fk("Customers", { display: "customerName", filter: {"field":"customerType","value":"Internal"} }), notes: "the INTERNAL customer opening the ticket (issue #308) — a second requirement-inheritance party: the ticket inherits requirements pinned to the project customer OR the applicant (the #226 customer gate widened to the pair; empty key = applies to all, Q1 unchanged). Since issue #350 also the buying side of the SLA-basis pair — the ticket's events and scopes follow the contracts where the applicant buys from the chosen Supplier (ticketAdmittedSLAs; blank = the dimension is skipped). Always Internal type (attribute-rule filter, Branches precedent); nullable — a ticket without an applicant inherits through the customer alone", constraints: ["FK"] }),
  attr("branchID", "FK", { rel: fk("Branches", { display: "branchName" }), notes: "The branch that RECEIVES the ticket's output (sv108, Rafael's conceptual fix) — chosen below the Applicant, options = the branches where the APPLICANT is registered (Branches.customerID, generic stored-key cascade). THE branch context of requirement inheritance: branch-pinned requirements apply exactly to this branch — the sv105/sv106 union (project ∪ customer/applicant/supplier branches) is superseded, and the SUPPLIER never feeds inheritance (a supplier must not impose requirements on a request it must itself resolve). Nullable — blank = the branch dimension is skipped. Since sv110 it ALSO gates the SLA basis (Rafael's rule: the contract filter is Applicant → Supplier → branch): an SLA pinned to another branch drops from the ticket's Event/Product Scope universe; a branch-less SLA is not branch-specific and stays (#316 posture)", constraints: ["FK"] }),
  attr("customerID", "FK", { rel: fk("Customers", { display: "customerName" }), notes: "Customer / requester — PK-keyed since v3-review R3; displays customerName since the geography attrs (and the customerTitle CONCAT) left Customers (issue #191)", constraints: ["FK"] }),
  attr("customerName", "mirror", { rel: mirror("Customers", "customerID", { display: "customerName" }), notes: "Display/report mirror of the linked customer (same pattern as Projects)", show: [false, false] }),
  attr("supplierID", "FK", { rel: fk("Customers", { display: "customerName" }), notes: "the supplying-party filter (issue #272; re-sourced by issue #281) — offered from the unit's customers grouped by customerType (generic stored-key cascade on Customers.businessUnitID; the #272 active-SLA sourcing via suppliersForTicketCustomer is retired); nullable. Since issue #350 the supplier is the supplying side of the SLA-basis pair — (SLA.customerID = Applicant, SLA.supplierID = Supplier) defines the ticket's contract universe (ticketAdmittedSLAs); no supplier = the dimension is skipped. Demo seeds re-keyed by migrate_ticket_sla_cascade.py to the applicant's covering contract's supplier", constraints: ["FK"], show: [false, false] }),
  attr("eventID", "FK", { rel: fk("Events", { display: "eventTitle" }), notes: "The Event select only offers events packaged by the payloads of the APPLICANT → SUPPLIER contracts (issue #350 — eventsForTicket in forms.js, superseding the #325 project universe): every Active SLA matching the exact pair, a blank side skips its dimension; the Customer no longer participates in SLA survival (it only filters the Projects select). No surviving SLA = no options; the field stays gated on Project as a form-flow anchor. Display fixed to eventTitle (eventName never existed).", constraints: ["FK"], show: [true, true] }),
  attr("payloadID", "FK", { rel: fk("Payload", { display: "payloadCode" }), notes: "multivalued — the dispatch package(s) RESOLVED for this ticket (issue #325, replaces the #192 via-eventID rollup; survivors re-sourced to the applicant-supplier contracts by #350): among the surviving SLAs' purchased payloads, those carrying the chosen event and packaging the chosen product scope (empty packaging = wildcard, Q1). The Event × Product Scope pick alone does not guarantee a payload, so the engine resolves and STORES the admitted set on save (applyDerivedUnits) — re-seeded by migrate_ticket_sla_cascade.py; no form input.", constraints: ["FK"] }),
  attr("productScopeID", "FK", { rel: fk("Product Scopes", { concat: [{"field":"productName"},{"lit":" | "},{"field":"scopeName"}] }), notes: "Product scope this ticket targets — NOT NULL since issue #243 (A2: without it the Jobs task rollup collapsed); picked among the scopes co-packaged with the chosen event in a same payload of the surviving APPLICANT → SUPPLIER contracts (issue #350 — productScopesForTicket in forms.js; no covering SLA = no options; a wildcard payload widens to the event's applicability, Q1). Stores the id — the display CONCAT resolves the names.", constraints: ["FK","NOT NULL"], show: [false, false] }),
  attr("constraintID", "FK", { rel: fk("Requirements", { display: "requirementName" }), notes: "multivalued — CONSTRAINTS picked on the wizard Request step (issue #359, REDEFINED 2026-09-08: the flag is an additional FILTER layer, not a manual addition — the #359 union into ticketRequirements is retired): options = Selectable-on-Tickets (Yes) + Active requirements whose businessUnitID names the ticket's unit (constraintsForTicketUnit in forms.js); the picks NARROW the Product Scope options to the scopes whose comprehensive PS-REQUIREMENTS set covers ALL selected constraints (AND — a filter narrows; none picked = unfiltered). Since sv109 (Rafael's deliberate-selection rule) the picks ALSO gate the inheritance: once the user ENGAGES the input (≥1 pick), the OFFERED selectables not picked are a deliberate exclusion and leave ticketRequirements — requirements never offered there inherit normally; ZERO picks = no decision, inheritance untouched (session decision — the demo seeds carry empty picks, 0 flips at rest; selectableConstraintIds in resolve.js is the shared offered-set core). Renamed from addedRequirementID (seeds empty)", constraints: ["FK"], show: [false, false] }),
  attr("forecastScopeID", "FK", { rel: fk("Forecast Scopes", { display: "forecastScopeRegistry" }), notes: "The demand line this ticket consumes (issue #243, link A1) — nullable: NULL = the ticket ran outside the forecast. DATA-ONLY since the 2026-09-03 input-removal round: the form's Forecast Scope select was eliminated (authored edit; the #243/#274 picker helper forecastScopesForTicket retired with it) — seeded/imported links keep feeding the Forecast Scopes consumption rollup and remaining balance.", constraints: ["FK"], show: [true, true] }),
  attr("slaID", "FK", { rel: fk("SLA", { display: "slaCode" }), notes: "multivalued — the governing contract(s), RESOLVED and STORED on save (issue #325, replaces the #191 via-customerID rollup; survival re-sourced by #350): the surviving SLAs that purchased at least one of the ticket's resolved payloads. Survival = the exact (Applicant, Supplier) pair over every Active SLA (session decision, superseding the #325 two-leg union): SLA.customerID names the Applicant AND SLA.supplierID = the Supplier; a blank side skips its dimension (the #308 null-applicant cohort keeps resolving). Re-seeded by migrate_ticket_sla_cascade.py; no form input.", constraints: ["FK"] }),
  attr("ticketDescription", "TEXT"),
  attr("processID", "VARCHAR", { rel: {"kind":"mirror","target":"Processes","via":null,"viaList":null,"display":"processName","concat":null,"filter":null}, notes: "Via eventID and productScopeID (issue #214): stored snapshot of process ids — the event's processes narrowed by the chosen product scope (a process with an empty productScopeID list covers every scope; no scope chosen = all of the event's processes, Q1). Re-seeded by migrate_ticket_scope_round.py, derived on save for UI-created tickets (applyDerivedUnits in forms.js). Drives the Processes/Tasks subitem tabs (via: processID); display resolves id → processName.", show: [false, false] }),
  attr("inputHandoutID", "mirror", { rel: {"kind":"ticketinputs","srcField":"processID","display":"handoutName"}, notes: "LIVE-derived, never stored (issue #280): the customer-provided inputs of this ticket — for each task of the ticket's processes, the ticket's inherited requirement set (#226) plus its admitted product-scope context (#332 — a procedure pinned to scopes the ticket does not admit is no candidate) narrow the procedures to exactly ONE (#270 AND coverage; GAP/ambiguous tasks contribute nothing), and the inputs in that procedure's customerInputID set (#324 per-procedure decision; pre-sv77 snapshots fall back to the retired handout flag) are collected, deduped. Drives the Inputs subitem tab (via: inputHandoutID — ticketInputHandouts in resolve.js, wired by mapSubitem).", show: [false, false] }),
  attr("products", "VARCHAR", { rel: {"kind":"mirror","target":"Product Scopes","via":null,"viaList":null,"display":"productName","concat":null,"filter":null}, notes: "Via the event's payloads (Payload.productScopeID) — stored snapshot re-seeded by migrate_workspace_activation.py" }),
  attr("scopes", "VARCHAR", { rel: {"kind":"mirror","target":"Product Scopes","via":null,"viaList":null,"display":"scopeName","concat":null,"filter":null}, notes: "Via the event's payloads (Payload.productScopeID) — stored snapshot re-seeded by migrate_workspace_activation.py" }),
  attr("requirementName", "mirror", { rel: {"kind":"inheritedreqs","srcField":"eventID","display":"requirementName"}, notes: "Live-derived (issue #226 — replaces the #192 stored snapshot): Active requirements AND-matched against the ticket's admitted payload chain — event → payloads under the customer's ACTIVE SLAs (lenient, productScopesForTicket posture) → product scopes (∩ the ticket's productScopeID when set) — plus the ticket's businessUnitID, that unit's served regions (Business Units.regionID), the ticket's inheritance parties — customer AND applicant, the #308 pair (the SUPPLIER is deliberately EXCLUDED since sv108: a supplier must not impose requirements on a request it must itself resolve) — the OUTPUT branch (the stored Tickets.branchID, sv108) and the region traces (the unit's served regions ∪ the output branch's region). Requirement keys: a DECLARED dimension constrains, an undeclared one does not (sv106 refinement — the sv99 strict reading was reverted; the #364 doctrine stays on the coverage sets). Deliberate divergence from the #192 seed: the unit gate reads the TICKET's unit, not ps.businessUnitID. A new aligned requirement surfaces on existing tickets automatically — but a requirement registered AFTER a dimension's 'all' snapshot needs the revisit the doctrine mandates. Deliberate-selection rule (sv109): with ≥1 Constraint picked, offered-but-unpicked selectables leave the set (zero picks = no decision).", show: [false, false] }),
  attr("taskID", "rollup", { notes: "Superseded: the old 3-key rollup (scopeID, productName, customerID) references fields Tasks no longer stores; ticket→task dispatch lives in the TICKET-PROCEDURE / INHERITED-REQUIREMENTS rules. Derived, never populated, hidden — removal candidate (#424).", show: [false, false] }),
  attr("ticketExecutionTime", "INT", { notes: "Stored execution time seeded from the task (#417: the former rule was seed documentation, not an engine rule)" }),
  attr("ticketOwner", "VARCHAR", { rel: userInput(), constraints: ["FK"] }),
  attr("ticketStatus", "ENUM", { rel: enumOf("Open", "InProgress", "Resolved", "Escalated", "Closed"), show: [true, true] }),
  attr("targetDate", "DATETIME", { notes: "When the ticket should be resolved", show: [true, true] }),
  attr("ticketCreatedAt", "DATETIME", { show: [false, false] }),
  attr("ticketClosedAt", "DATETIME", { notes: "nullable", show: [false, false] }),
  attr("jobs", "rollup", { rel: rollup("Jobs", "ticketID"), notes: "All Jobs associated with this ticket", show: [false, false] }),
]);

const projects = entity("Projects", "A project (contract or campaign) with customer, owner and status. Groups tickets and provides estimated vs. executed time roll-ups (ISO §8.3 / §8.4).", [
  attr("projectID", "INT", { notes: "Displayed as project number, e.g. \"0034\"", constraints: ["PK"], show: [false, false] }),
  attr("projectRegistryID", "VARCHAR", { notes: "Human registry code (PRJ-2026-001); projectID is the key. Displayed by Tickets.projectID (#417: was a second PK)", constraints: ["NOT NULL"], show: [true, true] }),
  attr("projectName", "VARCHAR", { notes: "Name of the project", show: [true, true] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "single valued — anchors the Customer/SLA cascade (issue #192); seeded from the project's customer", constraints: ["FK","NOT NULL"], show: [false, false] }),
  attr("customerID", "FK", { rel: fk("Customers", { display: "customerName" }), notes: "Name of the final/external client", constraints: ["FK","NOT NULL"], show: [true, true] }),
  attr("customerName", "mirror", { rel: mirror("Customers", "customerID", { display: "customerName" }), notes: "Merged with the former Client field — resolved from customerID; kept for downstream mirrors (Tickets, Jobs)", show: [false, false] }),
  attr("products", "rollup", { notes: "Products linked through tickets — intended chain Projects → Tickets → Products has no field (Tickets stores no productID). Derived, never populated, hidden — removal candidate (#424).", show: [false, false] }),
  attr("projectOwner", "FK", { rel: fk("People", { display: "userName" }), constraints: ["FK"], show: [true, true] }),
  attr("projectStatus", "ENUM", { rel: enumOf("In Progress", "Planning", "On Hold", "Closed"), show: [true, true] }),
  attr("ticketID", "rollup", { rel: rollup("Tickets", "projectID"), notes: "All tickets belonging to this project", show: [false, false] }),
  attr("jobID", "VARCHAR", { rel: {"kind":"mirror","target":"Tickets","via":null,"viaList":null,"display":"jobs","concat":null,"filter":null}, notes: "Via projectID", show: [true, true] }),
  attr("estimatedTime", "DECIMAL", { notes: "Stored planner estimate (seeded). Tickets carry no estimate field, so it cannot be summed live (#417)", show: [true, true] }),
  attr("executionTime", "DECIMAL", { notes: "Stored (seeded). A live SUM(ticketID.ticketExecutionTime) is possible but would change the shown numbers — kept stored by decision (#417)", show: [true, true] }),
]);

const jobs = entity("Jobs", "A Job is a concrete execution record assigning a person/role to a Ticket to perform a piece of work, tracking planned and actual dates, dependencies and status. Jobs are the primary source of actual usage data for the Control module (ISO §7.1.2).", [
  attr("jobID", "INT", { constraints: ["PK"], show: [false, false] }),
  attr("businessUnitID", "FK", { rel: fk("Business Units", { display: "businessUnitName" }), notes: "Form filter — narrows the Project options (pre-RBAC filter input, issue #346). Seeds: the ticket's unit (tools/migrate_prerbac_batch.py; census 240/240 ticket-unit == project-unit).", constraints: ["FK"], show: [false, false] }),
  attr("projectID", "FK", { rel: fk("Projects", { display: "projectName" }), notes: "Project the job belongs to — derived on save from the ticket since issue #244 (A14: the stored duplicate could drift; the Project select only narrows the ticket options)", constraints: ["FK","NOT NULL"], show: [false, false] }),
  attr("ticketID", "FK", { rel: fk("Tickets", { display: "ticketID" }), notes: "Ticket this job belongs to", constraints: ["FK","NOT NULL"] }),
  attr("scopeID", "rollup", { rel: rollup("Product Scopes", "ticketID", { display: "scopeName" }), notes: "Scope of the ticket's product scope", constraints: ["FK"] }),
  attr("productGroupID", "rollup", { rel: rollup("Product Scopes", "ticketID", { display: "productGroupName" }), notes: "Product group of the ticket's product scope", constraints: ["FK"] }),
  attr("projectName", "VARCHAR", { rel: mirror("Projects", "projectID", { display: "projectName" }), notes: "From ticket ID", show: [true, true] }),
  attr("customerID", "mirror", { rel: mirror("Projects", "projectID", { display: "customerName" }), notes: "From ticket ID", show: [true, true] }),
  attr("taskID", "FK", { rel: fk("Tasks", { display: "taskName" }), notes: "Stored task template (issue #243 — the value must be stable on the record, it anchors plannedExecutionTime; the old 3-key rollup collapsed to 6 tasks on the empty ticket scopes, A2). Options filtered by tasksForJob(ticket) in the form.", constraints: ["FK"] }),
  attr("jobName", "mirror", { rel: mirror("Tasks", "taskID", { display: "taskName" }), notes: "Task name of the job (#417: was a malformed rule; the stored copies equal Tasks.taskName and are now inert)", show: [false, true] }),
  attr("userID", "FK", { rel: fk("People", { display: "userName" }), notes: "Filtered by the roleID of the selected task template", constraints: ["FK"], show: [true, true] }),
  attr("roleID", "mirror", { rel: mirror("People", "userID", { display: "roleID" }), notes: "The allocated person's role (issue #244, A8 — a job has no role of its own: the old stored copy matched People in 0/187 rows and was dropped)", show: [true, true] }),
  attr("deliveryDate", "DATETIME", { notes: "Planned delivery date (A13 unswap — the notes were inverted)", show: [true, true] }),
  attr("startDate", "DATETIME", { notes: "Planned start date (A13 unswap — the notes were inverted; in the data it precedes deliveryDate, as it should)" }),
  attr("plannedExecutionTime", "DECIMAL", { rel: computed(null), notes: "Stamped on save from the chosen task's procedures (issue #244, A9) — the plan Performance measures must have existed", show: [true, true] }),
  attr("realStartDate", "DATETIME", { notes: "Actual start date" }),
  attr("realEndDate", "DATETIME", { notes: "Actual end date" }),
  attr("realExecutionTime", "DECIMAL", { rel: computed(null), notes: "Stored when the job transitions to Done: elapsed minus Stoped buffer" }),
  attr("jobBufferExecution", "DECIMAL", { notes: "Decimal hours the job sat in Stoped; subtracted from realExecutionTime" }),
  attr("stoppedAt", "DATETIME", { notes: "Bookkeeping: timestamp of the last transition INTO Stoped", show: [false, false] }),
  attr("customerName", "VARCHAR", { notes: "Stored copy of the job's project customer (#417: the former rule was an English sentence). Kept STORED because Jobs::Report-A (queries.js) groups by the raw row key — making it a mirror needs that report to resolve through the engine. Duplicates customerID's mirror — removal candidate once the report is fixed (#424).", show: [true, true] }),
  attr("squadName", "VARCHAR", { rel: computed("People") }),
  attr("predecessorJobID", "FK", { rel: fk("Jobs", { display: "jobName" }), notes: "Self-FK, nullable (issue #244, A6 — the predecesorJob residue in forms.js finally has an attribute): the job that must run before this one. Options: jobs of the same ticket.", constraints: ["FK"], show: [false, true] }),
  attr("dependencyType", "ENUM", { rel: enumOf("start-to-finish", "start-to-start", "finish-to-start", "finish-to-finish"), notes: "How this job depends on its predecessor — reuses the Workflows.indentationRule enum (issue #244)", show: [false, true] }),
  attr("jobStatus", "ENUM", { rel: enumOf("Queued", "Active", "Done", "Stoped"), show: [true, true] }),
  attr("jobOwner", "FK", { rel: fk("People", { display: "userName" }), notes: "Accountability owner (ISO 9001:2015 §5.3, §6.2.2(c))", constraints: ["FK"], show: [false, false] }),
]);

export const workspace = defineModule("Workspace", 6, [
  table(tickets, {
    visibility: "show",
    dashboardOrder: 1,
    reports: {
      "Report-A": {
        "graph_type": "bar",
        "rule": "Count of Tickets grouped by customerName",
        "filters": [
          "ticketStatus",
          "processID",
          "period"
        ]
      },
      "Report-B": {
        "graph_type": "donut",
        "rule": "Count of tickets grouped by scopeName",
        "filters": [
          "customerName",
          "period",
          "requirementName"
        ]
      }
    },
    form: formFor(tickets.entity, {
      steps: {
        "Parties": {
          "order": 1,
          "description": "Who is involved — the unit, the applicant opening the ticket, the customer, its project and the supplier answering it"
        },
        "Request": {
          "order": 2,
          "description": "What is requested — the event and product scope covered by the Applicant → Supplier contracts"
        },
        "Details": {
          "order": 3,
          "description": null
        }
      },
      fields: {
        "Business Unit": { attribute: "businessUnitID", widget: "selectgroups", tooltip: "Unit receiving the ticket — filters the customers", step: "Parties", rule: { groupBy: "businessSegmentName" } },
        "Applicant": { attribute: "applicantID", tooltip: "The internal customer opening the ticket — its requirements apply on top of the project customer's, and it is the buying side of the contract basis: the ticket's events and scopes follow the SLAs where the applicant buys from the chosen Supplier", step: "Parties" },
        "Branch": { attribute: "branchID", tooltip: "The Applicant's branch that will receive the ticket's output — branch-pinned requirements apply exactly to this branch (leave empty to skip the branch dimension)", step: "Parties", check: requires("Applicant"), rule: { filteredBy: "Applicant" } },
        "Customer": { attribute: "customerID", tooltip: "Filters the projects offered below — since issue #350 the ticket's events and scopes follow the Applicant → Supplier contracts, not the project's", step: "Parties", check: requires("Business Unit"), rule: { filteredBy: "businessUnitID" } },
        "Project": { attribute: "projectID", step: "Parties", check: requires("Customer"), rule: { filteredBy: "Customer" } },
        "Supplier": { attribute: "supplierID", widget: "selectgroups", tooltip: "The party responsible for resolving the issue — any customer of the unit; the supplying side of the contract basis: the ticket's events and scopes follow the SLAs where the Applicant buys from this supplier; leave empty to skip the supplier dimension", step: "Parties", check: requires("Business Unit"), rule: { list: true, groupBy: "customerType", filteredBy: "Business Unit" } },
        "Event": { attribute: "eventID", tooltip: "Only events packaged by the contracts between the Applicant and the Supplier are offered (issue #350) — leave a side empty to skip its dimension", step: "Request", check: requires("Project"), rule: { filteredBy: "Applicant + Supplier + Branch" } },
        "Constraints": { attribute: "constraintID", tooltip: "Filter the Product Scopes below by the requirements they must answer for (issue #359 redefined) — offered are the Selectable-on-Tickets requirements of this Business Unit; leave empty to see every admitted scope. The automatically inherited requirement set is not affected", step: "Request", check: requires("Business Unit"), rule: { list: true, multi: true, filteredBy: "Business Unit" } },
        "Product Scope": { attribute: "productScopeID", tooltip: "Only product scopes co-packaged with the chosen event in a payload of the Applicant → Supplier contracts — narrowed to the scopes answering for the selected Constraints (issue #359); the resolved payload and contract are stored on save", step: "Request", check: requires("Event"), rule: { filteredBy: "Event + Applicant + Supplier + Branch + Constraints" } },
        "Details": { attribute: "ticketDescription", step: "Details" },
        "Target Date": { attribute: "targetDate", widget: {"key":"date","hint":"shadcn-date picker"}, step: "Details" },
        "Status": { attribute: "ticketStatus", step: "Details" },
      },
    }),
    cards: {
      "Card 1-1": {
        "overview-display": true,
        "title": "Tickets opened in the last 5 days",
        "card-rules": {
          "main-data": "Show the total count of tickets created in the past five days",
          "trend-data": "how much ticket creation has changed during the last month",
          "detail-data": "total of tickets created in the current month"
        },
        "card-component": "shadcn-card",
        "card-tooltip": "Count of tickets created in the past 5 days"
      }
    },
    tableFilters: true,
    subitemTables: [
      {
        "tab-order": 1,
        "rule": "(via: processID)",
        "tab-name": "Processes",
        "tab-table": "Processes"
      },
      {
        "tab-order": 2,
        "rule": "ordered by taskIndentationID (via: processID)",
        "tab-name": "Tasks",
        "tab-table": "Tasks",
        "tab-columns": [
          "userID",
          "procedureExecutionTime"
        ]
      },
      {
        "tab-order": 3,
        "rule": "(via: inputHandoutID)",
        "tab-name": "Inputs",
        "tab-table": "Handouts"
      },
      {
        "tab-order": 4,
        "rule": "(via: requirementName)",
        "tab-name": "Requirements",
        "tab-table": "Requirements"
      }
    ],
  }),
  table(projects, {
    visibility: "show",
    dashboardOrder: 2,
    reports: {
      "Report-A": {
        "graph_type": "bar",
        "rule": "Estimated (tasks) vs real (jobs) execution time per Closed Projects",
        "filters": [
          "customerName",
          "projectStatus"
        ]
      }
    },
    form: formFor(projects.entity, {
      fields: {
        "Registry ID": { attribute: "projectRegistryID" },
        "Name": { attribute: "projectName" },
        "Business Unit": { attribute: "businessUnitID", widget: "selectgroups", tooltip: "Unit executing the project — filters the customers", rule: { groupBy: "businessSegmentName" } },
        "Customer": { attribute: "customerID", tooltip: "The paying customer of the contract", check: requires("Business Unit"), rule: { filteredBy: "businessUnitID" } },
        "Owner": { attribute: "projectOwner", widget: "selectgroups", rule: { groupBy: "function" } },
        "Status": { attribute: "projectStatus" },
      },
    }),
    cards: null,
    tableFilters: true,
    subitemTables: [
      "tickets"
    ],
  }),
  table(jobs, {
    visibility: "show",
    dashboardOrder: 3,
    reports: {
      "Report-A": {
        "overview-display": true,
        "graph_type": "bar chart - multiple",
        "rule": "plannedExecutionTime vs. realExecutionTime side by side grouped by customerName. Y = hours, X = customerName",
        "filters": {
          "fields": {
            "periodFrame": {
              "field-type": {
                "range-picker": "shadcn-Date Picker"
              },
              "tooltip": null,
              "default": "last six months from current date",
              "check": null,
              "field-rule": null
            },
            "scopeName": {
              "field-type": {
                "basic": "shadcn-combobox"
              },
              "tooltip": null,
              "default": "ALL",
              "check": null,
              "field-rule": "computed -> Scopes (via: eventTitle.field), (display: scopeName):  Multivalued field"
            },
            "eventTitle": {
              "field-type": {
                "combobox": "shadcn-comboboxGroups"
              },
              "tooltip": null,
              "default": "ALL",
              "check": null,
              "field-rule": "FK -> Events (display: eventName): Multivalued field"
            },
            "customerName": {
              "field-type": {
                "combobox": "shadcn-combobox"
              },
              "tooltip": null,
              "default": "ALL",
              "check": null,
              "field-rule": "FK -> Customers (display: customerName): Multivalued field"
            }
          }
        }
      },
      "Report-B": {
        "graph_type": "bar",
        "rule": "SUM(realExecutionTime) grouped by roleName",
        "filters": [
          "jobStatus (default = all)",
          "ticketID (default = all)",
          "period (default = last 6 months)"
        ]
      }
    },
    form: formFor(jobs.entity, {
      fields: {
        "Business Unit": { attribute: "businessUnitID", tooltip: "Pick the unit first — the Project options narrow to it (pre-RBAC filter input, issue #346)" },
        "Project": { attribute: "projectID", check: requires("Business Unit"), rule: { list: true, groupBy: "customerName", filteredBy: "Business Unit" } },
        "Ticket": { attribute: "ticketID", widget: {"key":"combobox","hint":"shadcn-comboboxGroups"}, check: requires("Project"), rule: { list: true, groupBy: "customerName", filteredBy: "Project" } },
        "Task": { attribute: "taskID", check: requires("Ticket"), rule: { filteredBy: "Ticket" } },
        "Responsible": { attribute: "userID", widget: {"key":"certified-responsible","hint":"custom"}, tooltip: "Certified people for the ticket's scope, product group and requirements (narrowed by the task)", check: requires("Ticket") },
        "Delivery Date": { attribute: "deliveryDate", widget: {"key":"datetime","hint":"shadcn-date picker"} },
        "Status": { attribute: "jobStatus" },
        "Predecessor": { attribute: "predecessorJobID", tooltip: "Job of the same ticket that must run before this one — optional", check: requires("Ticket"), rule: { note: "jobs of the same ticket" } },
        "Dependency": { attribute: "dependencyType", check: requires("Predecessor") },
      },
    }),
    cards: null,
    tableFilters: true,
    subitemTables: [],
  }),
]);
